MONEYGRAM_DM_MAPPING = {
    "WILL_CALL": "WILL_CALL",
    "DIRECT_TO_ACCT": "DIRECT_TO_ACCT",  # wallet / mobile money
    "BANK_DEPOSIT": "BANK_DEPOSIT",  # bank account
    "WILLCALL_TO": "WILLCALL_TO",
    "2_HOUR": "2_HOUR",
    "OVERNIGHT": "OVERNIGHT",
    "OVERNIGHT2ANY": "OVERNIGHT2ANY",
    "24_HOUR": "24_HOUR",
    "CARD_DEPOSIT": "CARD_DEPOSIT",
    "HOME_DELIVERY": "HOME_DELIVERY",
}

UNFUNDED = "UNFUNDED"
SENT = "SENT"
AVAILABLE = "AVAILABLE"
IN_TRANSIT = "IN TRANSIT"
RECEIVED = "RECEIVED"
DELIVERED = "DELIVERED"
PROCESSING = "PROCESSING"
REJECTED = "REJECTED"
REFUNDED = "REFUNDED"
CLOSED = "CLOSED"
