<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.westernunion.com/DSDVerification_H2H" xmlns:xrsi="http://www.westernunion.com/schema/xrsi" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="DSDVerification_Service_H2H" targetNamespace="http://www.westernunion.com/DSDVerification_H2H">
  <wsdl:types>
    <xsd:schema xmlns:mrm="http://www.westernunion.com/DSDVerification" targetNamespace="http://www.westernunion.com/DSDVerification" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.westernunion.com/schema/xrsi" schemaLocation="../schema/XRSIDSDataVerificationRequest.xsd"/>
      <xsd:import namespace="http://www.westernunion.com/schema/xrsi" schemaLocation="../schema/XRSIDSDataVerificationReply.xsd"/>
      <xsd:import namespace="http://www.westernunion.com/schema/xrsi" schemaLocation="../schema/XRSIErrorReply.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="DSDVerification_in">
    <wsdl:part element="xrsi:dsd-request" name="dsd-request"/>
  </wsdl:message>
  <wsdl:message name="DSDVerification_out">
    <wsdl:part element="xrsi:dsd-reply" name="dsd-reply"/>
  </wsdl:message>
  <wsdl:message name="DSDVerification_fault1">
    <wsdl:part element="xrsi:error-reply" name="error-reply"/>
  </wsdl:message>
  <wsdl:portType name="DSDVerificationPortType">
    <wsdl:operation name="DSDVerification">
      <wsdl:input message="tns:DSDVerification_in" name="DSDVerification_Input"/>
      <wsdl:output message="tns:DSDVerification_out" name="DSDVerification_Output"/>
      <wsdl:fault message="tns:DSDVerification_fault1" name="DSDVerification_Fault"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="DSDVerification_H2H_SOAP_HTTP_Binding" type="tns:DSDVerificationPortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="DSDVerification">
      <soap:operation/>
      <wsdl:input name="DSDVerification_Input">
        <soap:body parts="dsd-request" use="literal"/>
      </wsdl:input>
      <wsdl:output name="DSDVerification_Output">
        <soap:body parts="dsd-reply" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="DSDVerification_Fault">
        <soap:fault name="DSDVerification_Fault" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="DSDVerification_Service_H2H">
    <wsdl:port binding="tns:DSDVerification_H2H_SOAP_HTTP_Binding" name="SOAP_HTTP_Port">
      <soap:address location="http://www.westernunion.com/DSDVerification_Service_H2H"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
