<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.westernunion.com/FLAAuthorization"
	xmlns:xrsi="http://www.westernunion.com/schema/xrsi" xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
	xmlns:xsi="http://www.westernunion.com/schema/xrsi"
	name="FLAAuthorization_Service" targetNamespace="http://www.westernunion.com/FLAAuthorization">
	<wsdl:types>
		<xsd:schema xmlns:mrm="http://www.westernunion.com/FLAAuthorization" targetNamespace="http://www.westernunion.com/FLAAuthorization" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="http://www.westernunion.com/schema/xrsi" schemaLocation="../schema/XRSIErrorReply.xsd"/>
			<xsd:import namespace="http://www.westernunion.com/schema/xrsi"  schemaLocation="../schema/XRSIFLAAuthorizationReply.xsd" />
			<xsd:import namespace="http://www.westernunion.com/schema/xrsi" schemaLocation="../schema/XRSIFLAAuthorizationRequest.xsd" />
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="FLAAuthorization_in">
		<wsdl:part element="xrsi:fla-authorization-request" name="fla-authorization-request" />
	</wsdl:message>
	<wsdl:message name="FLAAuthorization_out">
		<wsdl:part element="xrsi:fla-authorization-reply" name="fla-authorization-reply" />
	</wsdl:message>
	<wsdl:message name="FLAAuthorization_fault1">
		<wsdl:part element="xsi:error-reply" name="error-reply" />
	</wsdl:message>
	<wsdl:portType name="FLAAuthorizationPortType">
		<wsdl:operation name="FLAAuthorization">
			<wsdl:input message="tns:FLAAuthorization_in" name="FLAAuthorization_Input" />
			<wsdl:output message="tns:FLAAuthorization_out" name="FLAAuthorization_Output" />
			<wsdl:fault message="tns:FLAAuthorization_fault1" name="FLAAuthorization_Fault" />
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="FLAAuthorization_SOAP_HTTP_Binding"
		type="tns:FLAAuthorizationPortType">
		<soap:binding style="document"
			transport="http://schemas.xmlsoap.org/soap/http" />
		<wsdl:operation name="FLAAuthorization">
			<soap:operation />
			<wsdl:input name="FLAAuthorization_Input">
				<soap:body parts="fla-authorization-request" use="literal"/>
			</wsdl:input>
			<wsdl:output name="FLAAuthorization_Output">
				<soap:body parts="fla-authorization-reply" use="literal"/>
			</wsdl:output>
			<wsdl:fault name="FLAAuthorization_Fault">
				<soap:fault name="FLAAuthorization_Fault" use="literal"/>
			</wsdl:fault>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="FLAAuthorization_Service">
		<wsdl:port binding="tns:FLAAuthorization_SOAP_HTTP_Binding" name="SOAP_HTTP_Port">
			<soap:address location="http://www.westernunion.com/FLAAuthorization_Service" />
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
