<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.westernunion.com/FulfillSendSearch_H2H" xmlns:xrsi="http://www.westernunion.com/schema/xrsi" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="FulfillSendSearch_Service_H2H" targetNamespace="http://www.westernunion.com/FulfillSendSearch_H2H">
  <wsdl:types>
    <xsd:schema xmlns:mrm="http://www.westernunion.com/FulfillSendSearch" targetNamespace="http://www.westernunion.com/FulfillSendSearch" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.westernunion.com/schema/xrsi" schemaLocation="../schema/XRSIErrorReply.xsd"/>
      <xsd:import namespace="http://www.westernunion.com/schema/xrsi" schemaLocation="../schema/XRSIStagedSendMoneySearchReply.xsd"/>
      <xsd:import namespace="http://www.westernunion.com/schema/xrsi" schemaLocation="../schema/XRSIStagedSendMoneySearchRequest.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="FulfillSendSearch_in">
    <wsdl:part element="xrsi:staged-send-money-search-request" name="staged-send-money-search-request"/>
  </wsdl:message>
  <wsdl:message name="FulfillSendSearch_out">
    <wsdl:part element="xrsi:staged-send-money-search-reply" name="staged-send-money-search-reply"/>
  </wsdl:message>
  <wsdl:message name="FulfillSendSearch_fault1">
    <wsdl:part element="xrsi:error-reply" name="error-reply"/>
  </wsdl:message>
  <wsdl:portType name="FulfillSendSearchPortType">
    <wsdl:operation name="FulfillSendSearch">
      <wsdl:input message="tns:FulfillSendSearch_in" name="FulfillSendSearch_Input"/>
      <wsdl:output message="tns:FulfillSendSearch_out" name="FulfillSendSearch_Output"/>
      <wsdl:fault message="tns:FulfillSendSearch_fault1" name="FulfillSendSearch_Fault"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="FulfillSendSearch_H2H_SOAP_HTTP_Binding" type="tns:FulfillSendSearchPortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="FulfillSendSearch">
      <soap:operation soapAction="FulfillSendSearch"/>
      <wsdl:input name="FulfillSendSearch_Input">
        <soap:body parts="staged-send-money-search-request" use="literal"/>
      </wsdl:input>
      <wsdl:output name="FulfillSendSearch_Output">
        <soap:body parts="staged-send-money-search-reply" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="FulfillSendSearch_Fault">
        <soap:fault name="FulfillSendSearch_Fault" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="FulfillSendSearch_Service_H2H">
    <wsdl:port binding="tns:FulfillSendSearch_H2H_SOAP_HTTP_Binding" name="SOAP_HTTP_Port">
      <soap:address location="http://www.westernunion.com/FulfillSendSearch_Service_H2H"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
