<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.westernunion.com/FusionGoShopping_Service_H2H" xmlns:xrsi="http://www.westernunion.com/schema/xrsi" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="FusionGoShopping_Service_H2H" targetNamespace="http://www.westernunion.com/FusionGoShopping_Service_H2H">
  <wsdl:types>         
    <xsd:schema xmlns:mrm="http://www.westernunion.com/FusionGoShopping_Service_H2H" targetNamespace="http://www.westernunion.com/FusionGoShopping_Service_H2H" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.westernunion.com/schema/xrsi" schemaLocation="../schema/XRSIFusionGoShoppingReply.xsd"/>
      <xsd:import namespace="http://www.westernunion.com/schema/xrsi" schemaLocation="../schema/XRSIErrorReply.xsd"/>
      <xsd:import namespace="http://www.westernunion.com/schema/xrsi" schemaLocation="../schema/XRSIFusionGoShoppingRequest.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="fusionGoShopping_in">
    <wsdl:part element="xrsi:fusion-go-shopping-request" name="fusion-go-shopping-request"/>
  </wsdl:message>
  <wsdl:message name="fusionGoShopping_out">
    <wsdl:part element="xrsi:fusion-go-shopping-reply" name="fusion-go-shopping-reply"/>
  </wsdl:message>
  <wsdl:message name="fusionGoShopping_fault1">
    <wsdl:part element="xrsi:error-reply" name="error-reply"/>
  </wsdl:message>
  <wsdl:portType name="FusionGoShopping_Service_PortType">
    <wsdl:operation name="FusionGoShopping">
      <wsdl:input message="tns:fusionGoShopping_in" name="fusionGoShopping_Input"/>
      <wsdl:output message="tns:fusionGoShopping_out" name="fusionGoShopping_Output"/>
      <wsdl:fault message="tns:fusionGoShopping_fault1" name="fusionGoShopping_Fault"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="FusionGoShopping_H2H_SOAP_HTTP_Binding" type="tns:FusionGoShopping_Service_PortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="FusionGoShopping">
      <soap:operation soapAction="FusionGoShopping"/>
      <wsdl:input name="fusionGoShopping_Input">
        <soap:body parts="fusion-go-shopping-request" use="literal"/>
      </wsdl:input>
      <wsdl:output name="fusionGoShopping_Output">
        <soap:body parts="fusion-go-shopping-reply" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="fusionGoShopping_Fault">
        <soap:fault name="fusionGoShopping_Fault" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="FusionGoShopping_Service_H2H">
    <wsdl:port binding="tns:FusionGoShopping_H2H_SOAP_HTTP_Binding" name="SOAP_HTTP_Port">
      <soap:address location="http://localhost:7080/FusionGoShopping_Service_H2H"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
