<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.westernunion.com/GetDocument"
	xmlns:xrsi="http://www.westernunion.com/kyc/schema/xrsi" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="GetDocument_Service_H2H"
	xmlns:xsi="http://www.westernunion.com/schema/xrsi" 
	targetNamespace="http://www.westernunion.com/GetDocument">
	<wsdl:types>
		<xsd:schema xmlns:mrm="http://www.westernunion.com/GetDocument" targetNamespace="http://www.westernunion.com/GetDocument" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="http://www.westernunion.com/schema/xrsi" schemaLocation="../schema/XRSIErrorReply.xsd"/>
			<xsd:import namespace="http://www.westernunion.com/kyc/schema/xrsi"  schemaLocation="../schema/XRSIGetDocumentRequest.xsd" />
			<xsd:import namespace="http://www.westernunion.com/kyc/schema/xrsi" schemaLocation="../schema/XRSIGetDocumentReply.xsd" />
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="GetDocument_in">
		<wsdl:part element="xrsi:get_document_request" name="get_document_request" />
	</wsdl:message>
	<wsdl:message name="GetDocument_out">
		<wsdl:part element="xrsi:get_document_reply" name="get_document_reply" />
	</wsdl:message>
	<wsdl:message name="GetDocument_fault1">
		<wsdl:part element="xsi:error-reply" name="error-reply" />
	</wsdl:message>
	<wsdl:portType name="GetDocumentPortType">
		<wsdl:operation name="GetDocument">
			<wsdl:input message="tns:GetDocument_in" name="GetDocument_Input" />
			<wsdl:output message="tns:GetDocument_out" name="GetDocument_Output" />
			<wsdl:fault message="tns:GetDocument_fault1" name="GetDocument_Fault" />
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="GetDocument_SOAP_HTTP_Binding"
		type="tns:GetDocumentPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" />
		<wsdl:operation name="GetDocument">
			<soap:operation />
			<wsdl:input name="GetDocument_Input">
				<soap:body parts="get_document_request" use="literal" />
			</wsdl:input>
			<wsdl:output name="GetDocument_Output">
				<soap:body parts="get_document_reply" use="literal" />
			</wsdl:output>
			<wsdl:fault name="GetDocument_Fault">
				<soap:fault name="GetDocument_Fault" use="literal" />
			</wsdl:fault>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="GetDocument_Service_H2H">
		<wsdl:port binding="tns:GetDocument_SOAP_HTTP_Binding" name="SOAP_HTTP_Port">
			<soap:address location="http://www.westernunion.com/GetDocument_Service_H2H" />
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
