<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.westernunion.com/MakePaymentStore_Service_H2H" xmlns:xrsi="http://www.westernunion.com/schema/xrsi" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="MakePaymentValidate_Service_H2H" targetNamespace="http://www.westernunion.com/MakePaymentStore_Service_H2H">
  <wsdl:types>
    <xsd:schema xmlns:mrm="http://www.westernunion.com/MakePaymentStore_Service_H2H" targetNamespace="http://www.westernunion.com/MakePaymentStore_Service_H2H" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.westernunion.com/schema/xrsi" schemaLocation="../schema/XRSIMakePaymentStoreReply.xsd"/>
      <xsd:import namespace="http://www.westernunion.com/schema/xrsi" schemaLocation="../schema/XRSIErrorReply.xsd"/>
      <xsd:import namespace="http://www.westernunion.com/schema/xrsi" schemaLocation="../schema/XRSIMakePaymentStoreRequest.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="makePaymentStore_in">
    <wsdl:part element="xrsi:make-payment-store-request" name="make-payment-store-request"/>
  </wsdl:message>
  <wsdl:message name="makePaymentStore_out">
    <wsdl:part element="xrsi:make-payment-store-reply" name="make-payment-store-reply"/>
  </wsdl:message>
  <wsdl:message name="makePaymentStore_fault1">
    <wsdl:part element="xrsi:error-reply" name="error-reply"/>
  </wsdl:message>
  <wsdl:portType name="MakePaymentStore_Service_PortType">
    <wsdl:operation name="makePaymentStore">
      <wsdl:input message="tns:makePaymentStore_in" name="makePaymentStore_Input"/>
      <wsdl:output message="tns:makePaymentStore_out" name="makePaymentStore_Output"/>
      <wsdl:fault message="tns:makePaymentStore_fault1" name="makePaymentStore_Fault"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="MakePaymentStore_H2H_SOAP_HTTP_Binding" type="tns:MakePaymentStore_Service_PortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="makePaymentStore">
      <soap:operation soapAction="MakePaymentStoreService"/>
      <wsdl:input name="makePaymentStore_Input">
        <soap:body parts="make-payment-store-request" use="literal"/>
      </wsdl:input>
      <wsdl:output name="makePaymentStore_Output">
        <soap:body parts="make-payment-store-reply" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="makePaymentStore_Fault">
        <soap:fault name="makePaymentStore_Fault" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="MakePaymentStore_Service_H2H">
    <wsdl:port binding="tns:MakePaymentStore_H2H_SOAP_HTTP_Binding" name="SOAP_HTTP_Port">
      <soap:address location="http://localhost:7081/MakePaymentStore_Service_H2H"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
