<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.westernunion.com/ModifySendMoney_H2H" xmlns:xrsi="http://www.westernunion.com/schema/xrsi" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="ModifySendMoney_MSet" targetNamespace="http://www.westernunion.com/ModifySendMoney_H2H">
  <wsdl:types>
    <xsd:schema xmlns:mrm="http://www.westernunion.com/ModifySendMoney" targetNamespace="http://www.westernunion.com/ModifySendMoney" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.westernunion.com/schema/xrsi" schemaLocation="../schema/XRSIErrorReply.xsd"/>
      <xsd:import namespace="http://www.westernunion.com/schema/xrsi" schemaLocation="../schema/XRSIModifySendMoneyReply.xsd"/>
      <xsd:import namespace="http://www.westernunion.com/schema/xrsi" schemaLocation="../schema/XRSIModifySendMoneyRequest.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="ModifySendMoney_in">
    <wsdl:part element="xrsi:modify-send-money-request" name="modify-send-money-request"/>
  </wsdl:message>
  <wsdl:message name="ModifySendMoney_out">
    <wsdl:part element="xrsi:modify-send-money-reply" name="modify-send-money-reply"/>
  </wsdl:message>
  <wsdl:message name="ModifySendMoney_fault1">
    <wsdl:part element="xrsi:error-reply" name="error-reply"/>
  </wsdl:message>
  <wsdl:portType name="ModifySendMoneyPortType">
    <wsdl:operation name="ModifySendMoney">
      <wsdl:input message="tns:ModifySendMoney_in" name="ModifySendMoney_Input"/>
      <wsdl:output message="tns:ModifySendMoney_out" name="ModifySendMoney_Output"/>
      <wsdl:fault message="tns:ModifySendMoney_fault1" name="ModifySendMoney_Fault"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="ModifySendMoney_H2H_SOAP_HTTP_Binding" type="tns:ModifySendMoneyPortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="ModifySendMoney">
      <soap:operation soapAction="ModifySendMoneyAction"/>
      <wsdl:input name="ModifySendMoney_Input">
        <soap:body parts="modify-send-money-request" use="literal"/>
      </wsdl:input>
      <wsdl:output name="ModifySendMoney_Output">
        <soap:body parts="modify-send-money-reply" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="ModifySendMoney_Fault">
        <soap:fault name="ModifySendMoney_Fault" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="ModifySendMoney_MSetSOAP_HTTP_Service">
    <wsdl:port binding="tns:ModifySendMoney_H2H_SOAP_HTTP_Binding" name="SOAP_HTTP_Port">
      <soap:address location="http://www.westernunion.com/ModifySendMoney_Service_H2H"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
