<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.westernunion.com/MyWULookup_H2H" xmlns:xrsi="http://www.westernunion.com/schema/xrsi" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="MyWULookup_Service_H2H" targetNamespace="http://www.westernunion.com/MyWULookup_H2H">
  <wsdl:types>
    <xsd:schema xmlns:mrm="http://www.westernunion.com/MyWULookup_H2H" targetNamespace="http://www.westernunion.com/MyWULookup_H2H" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.westernunion.com/schema/xrsi" schemaLocation="../schema/XRSIErrorReply.xsd"/>
      <xsd:import namespace="http://www.westernunion.com/schema/xrsi" schemaLocation="../schema/XRSIMyWULookupReply.xsd"/>
      <xsd:import namespace="http://www.westernunion.com/schema/xrsi" schemaLocation="../schema/XRSIMyWULookupRequest.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="MyWULookup_in">
    <wsdl:part element="xrsi:my-wu-lookup-request" name="my-wu-lookup-request"/>
  </wsdl:message>
  <wsdl:message name="MyWULookup_out">
    <wsdl:part element="xrsi:my-wu-lookup-reply" name="my-wu-lookup-reply"/>
  </wsdl:message>
  <wsdl:message name="MyWULookup_fault1">
    <wsdl:part element="xrsi:error-reply" name="error-reply"/>
  </wsdl:message>
  <wsdl:portType name="MyWULookupPortType">
    <wsdl:operation name="MyWULookup">
      <wsdl:input message="tns:MyWULookup_in" name="MyWULookup_Input"/>
      <wsdl:output message="tns:MyWULookup_out" name="MyWULookup_Output"/>
      <wsdl:fault message="tns:MyWULookup_fault1" name="MyWULookup_Fault"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="MyWULookup_H2H_SOAP_HTTP_Binding" type="tns:MyWULookupPortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="MyWULookup">
      <soap:operation/>
      <wsdl:input name="MyWULookup_Input">
        <soap:body parts="my-wu-lookup-request" use="literal"/>
      </wsdl:input>
      <wsdl:output name="MyWULookup_Output">
        <soap:body parts="my-wu-lookup-reply" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="MyWULookup_Fault">
        <soap:fault name="MyWULookup_Fault" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="MyWULookup_Service_H2H">
    <wsdl:port binding="tns:MyWULookup_H2H_SOAP_HTTP_Binding" name="SOAP_HTTP_Port">
      <soap:address location="http://www.westernunion.com/MyWULookup_Service_H2H"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
