<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.westernunion.com/SignOn_H2H" xmlns:xrsi="http://www.westernunion.com/schema/xrsi" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="SignOn_Service_H2H" targetNamespace="http://www.westernunion.com/SignOn_H2H">
  <wsdl:types>
    <xsd:schema xmlns:mrm="http://tempuri.org/Request_Reply_MSet" targetNamespace="http://tempuri.org/Request_Reply_MSet" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.westernunion.com/schema/xrsi" schemaLocation="../schema/XRSIErrorReply.xsd"/>
      <xsd:import namespace="http://www.westernunion.com/schema/xrsi" schemaLocation="../schema/XRSINewSignonRequest.xsd"/>
      <xsd:import namespace="http://www.westernunion.com/schema/xrsi" schemaLocation="../schema/XRSINewSignonReply.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="signOn_in">
    <wsdl:part element="xrsi:signon-request" name="signon-request"/>
  </wsdl:message>
  <wsdl:message name="signOn_out">
    <wsdl:part element="xrsi:signon-reply" name="signon-reply"/>
  </wsdl:message>
  <wsdl:message name="signOn_fault1">
    <wsdl:part element="xrsi:error-reply" name="error-reply"/>
  </wsdl:message>
  <wsdl:portType name="SignOnPortType">
    <wsdl:operation name="signOn">
      <wsdl:input message="tns:signOn_in" name="signOn_Input"/>
      <wsdl:output message="tns:signOn_out" name="signOn_Output"/>
      <wsdl:fault message="tns:signOn_fault1" name="signOn_Fault"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="Signon_H2H_SOAP_HTTP_Binding" type="tns:SignOnPortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="signOn">
      <soap:operation/>
      <wsdl:input name="signOn_Input">
        <soap:body parts="signon-request" use="literal"/>
      </wsdl:input>
      <wsdl:output name="signOn_Output">
        <soap:body parts="signon-reply" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="signOn_Fault">
        <soap:fault name="signOn_Fault" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="SignOn_Service_H2H">
    <wsdl:port binding="tns:Signon_H2H_SOAP_HTTP_Binding" name="SOAP_HTTP_Port">
      <soap:address location="http://www.westernunion.com/SignOn_Service_H2H"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
