<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.westernunion.com/OperatorRegistration_H2H" xmlns:xrsi="http://www.westernunion.com/operator/schema/xrsi" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.westernunion.com/schema/xrsi" name="OperatorRegistration_Service_H2H" targetNamespace="http://www.westernunion.com/OperatorRegistration_H2H">
  <wsdl:types>
    <xsd:schema xmlns:mrm="http://www.westernunion.com/OperatorRegistration_H2H" targetNamespace="http://www.westernunion.com/OperatorRegistration_H2H" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.westernunion.com/operator/schema/xrsi" schemaLocation="../schema/XRSIOperatorTrainingDetailRequest.xsd"/>
      <xsd:import namespace="http://www.westernunion.com/schema/xrsi" schemaLocation="../schema/XRSIErrorReply.xsd"/>
      <xsd:import namespace="http://www.westernunion.com/operator/schema/xrsi" schemaLocation="../schema/XRSIOperatorTrainingDetailReply.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="OperatorTrainingDetail_in">
    <wsdl:part element="xrsi:operator_trainingdetail_request" name="operator_trainingdetail_request"/>
  </wsdl:message>
  <wsdl:message name="OperatorTrainingDetail_out">
    <wsdl:part element="xrsi:operator_trainingdetail_reply" name="operator_trainingdetail_reply"/>
  </wsdl:message>
  <wsdl:message name="OperatorTrainingDetail_fault">
    <wsdl:part element="xsi:error-reply" name="error-reply"/>
  </wsdl:message>
  <wsdl:portType name="OperatorTrainingDetailPortType">
    <wsdl:operation name="OperatorTrainingDetail">
      <wsdl:input message="tns:OperatorTrainingDetail_in" name="OperatorTrainingDetail_Input"/>
      <wsdl:output message="tns:OperatorTrainingDetail_out" name="OperatorTrainingDetail_Output"/>
      <wsdl:fault message="tns:OperatorTrainingDetail_fault" name="OperatorTrainingDetail_Fault"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="OperatorTrainingDetail_H2H_SOAP_HTTP_Binding" type="tns:OperatorTrainingDetailPortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="OperatorTrainingDetail">
      <soap:operation soapAction="OperatorTrainingDetail_Action"/>
      <wsdl:input name="OperatorTrainingDetail_Input">
        <soap:body parts="operator_trainingdetail_request" use="literal"/>
      </wsdl:input>
      <wsdl:output name="OperatorTrainingDetail_Output">
        <soap:body parts="operator_trainingdetail_reply" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="OperatorTrainingDetail_Fault">
        <soap:fault name="OperatorTrainingDetail_Fault" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="OperatorTrainingDetail_Service_H2H">
    <wsdl:port binding="tns:OperatorTrainingDetail_H2H_SOAP_HTTP_Binding" name="SOAP_HTTP_Port">
      <soap:address location="http://www.westernunion.com/OperatorTrainingDetail_Service_H2H"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
