<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.westernunion.com/Search_H2H" xmlns:xrsi="http://www.westernunion.com/schema/xrsi" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="Search_Service_H2HService" targetNamespace="http://www.westernunion.com/Search_H2H">
  <wsdl:types>
    <xsd:schema xmlns:mrm="http://www.westernunion.com/Search_H2H" targetNamespace="http://www.westernunion.com/Search_H2H" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.westernunion.com/schema/xrsi" schemaLocation="../schema/XRSISearchRequest.xsd"/>
      <xsd:import namespace="http://www.westernunion.com/schema/xrsi" schemaLocation="../schema/XRSIErrorReply.xsd"/>
      <xsd:import namespace="http://www.westernunion.com/schema/xrsi" schemaLocation="../schema/XRSISearchReply.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="Search_in">
    <wsdl:part element="xrsi:search-request" name="search-request"/>
  </wsdl:message>
  <wsdl:message name="Search_out">
    <wsdl:part element="xrsi:search-reply" name="search-reply"/>
  </wsdl:message>
  <wsdl:message name="Search_fault1">
    <wsdl:part element="xrsi:error-reply" name="error-reply"/>
  </wsdl:message>
  <wsdl:portType name="SearchPortType">
    <wsdl:operation name="Search">
      <wsdl:input message="tns:Search_in" name="Search_Input"/>
      <wsdl:output message="tns:Search_out" name="Search_Output"/>
      <wsdl:fault message="tns:Search_fault1" name="Search_Fault"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="Search_H2H_SOAP_HTTP_Binding" type="tns:SearchPortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="Search">
      <soap:operation/>
      <wsdl:input name="Search_Input">
        <soap:body parts="search-request" use="literal"/>
      </wsdl:input>
      <wsdl:output name="Search_Output">
        <soap:body parts="search-reply" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="Search_Fault">
        <soap:fault name="Search_Fault" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="Search_Service_H2H">
    <wsdl:port binding="tns:Search_H2H_SOAP_HTTP_Binding" name="SOAP_HTTP_Port">
      <soap:address location="https://wugateway2pi.westernunion.com/Search_Service_H2H"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
