<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.westernunion.com/SendMoneyValidate_H2H" xmlns:xrsi="http://www.westernunion.com/schema/xrsi" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="sendmoneyValidation_Service_H2H" targetNamespace="http://www.westernunion.com/SendMoneyValidate_H2H">
  <wsdl:types>
    <xsd:schema xmlns:mrm="http://www.westernunion.com/SendMoneyValidate" targetNamespace="http://www.westernunion.com/SendMoneyValidate" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.westernunion.com/schema/xrsi" schemaLocation="../schema/XRSISendMoneyValidationRequest.xsd"/>
      <xsd:import namespace="http://www.westernunion.com/schema/xrsi" schemaLocation="../schema/XRSISendMoneyValidationReply.xsd"/>
      <xsd:import namespace="http://www.westernunion.com/schema/xrsi" schemaLocation="../schema/XRSIErrorReply.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="sendmoneyValidation_in">
    <wsdl:part element="xrsi:send-money-validation-request" name="send-money-validation-request"/>
  </wsdl:message>
  <wsdl:message name="sendmoneyValidation_out">
    <wsdl:part element="xrsi:send-money-validation-reply" name="send-money-validation-reply"/>
  </wsdl:message>
  <wsdl:message name="sendmoneyValidation_fault1">
    <wsdl:part element="xrsi:error-reply" name="error-reply"/>
  </wsdl:message>
  <wsdl:portType name="SendMoneyValidatePortType">
    <wsdl:operation name="sendmoneyValidation">
      <wsdl:input message="tns:sendmoneyValidation_in" name="sendmoneyValidation_Input"/>
      <wsdl:output message="tns:sendmoneyValidation_out" name="sendmoneyValidation_Output"/>
      <wsdl:fault message="tns:sendmoneyValidation_fault1" name="sendmoneyValidation_Fault"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="SMValidation_H2H_SOAP_HTTP_Binding" type="tns:SendMoneyValidatePortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="sendmoneyValidation">
      <soap:operation/>
      <wsdl:input name="sendmoneyValidation_Input">
        <soap:body parts="send-money-validation-request" use="literal"/>
      </wsdl:input>
      <wsdl:output name="sendmoneyValidation_Output">
        <soap:body parts="send-money-validation-reply" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="sendmoneyValidation_Fault">
        <soap:fault name="sendmoneyValidation_Fault" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="SendmoneyValidation_Service_H2H">
    <wsdl:port binding="tns:SMValidation_H2H_SOAP_HTTP_Binding" name="SOAP_HTTP_Port">
      <soap:address location="https://wugateway2pi.westernunion.com/SendmoneyValidation_Service_H2H"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
