<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xrsi="http://www.westernunion.com/schema/xrsi" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.westernunion.com/VigoShopping_Service_H2H" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="VigoShopping_Service_H2H" targetNamespace="http://www.westernunion.com/VigoShopping_Service_H2H">
  <wsdl:types>
    <xsd:schema xmlns:mrm="http://www.westernunion.com/VigoShopping_Service_H2H" targetNamespace="http://www.westernunion.com/VigoShopping_Service_H2H" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.westernunion.com/schema/xrsi" schemaLocation="../schema/XRSIErrorReply.xsd"/>
      <xsd:import namespace="http://www.westernunion.com/schema/xrsi" schemaLocation="../schema/XRSIVigoGoShoppingRequest.xsd"/>
      <xsd:import namespace="http://www.westernunion.com/schema/xrsi" schemaLocation="../schema/XRSIVigoGoShoppingReply.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="VigoShopping_Service_H2H_in">
    <wsdl:part element="xrsi:vigo-goshopping-request" name="vigo-goshopping-request"/>
  </wsdl:message>
  <wsdl:message name="VigoShopping_Service_H2H_out">
    <wsdl:part element="xrsi:vigo-goshopping-reply" name="vigo-goshopping-reply"/>
  </wsdl:message>
  <wsdl:message name="VigoShopping_Service_H2H_fault1">
    <wsdl:part element="xrsi:error-reply" name="error-reply"/>
  </wsdl:message>
  <wsdl:portType name="VigoShoppingPortType">
    <wsdl:operation name="VigoShopping_Service_H2H">
      <wsdl:input message="tns:VigoShopping_Service_H2H_in" name="VigoShopping_Service_H2H_Input"/>
      <wsdl:output message="tns:VigoShopping_Service_H2H_out" name="VigoShopping_Service_H2H_Output"/>
      <wsdl:fault message="tns:VigoShopping_Service_H2H_fault1" name="VigoShopping_Service_H2H_Fault"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="VigoShopping_Service_H2H_HTTP_Binding" type="tns:VigoShoppingPortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="VigoShopping_Service_H2H">
      <soap:operation/>
      <wsdl:input name="VigoShopping_Service_H2H_Input">
        <soap:body parts="vigo-goshopping-request" use="literal"/>
      </wsdl:input>
      <wsdl:output name="VigoShopping_Service_H2H_Output">
        <soap:body parts="vigo-goshopping-reply" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="VigoShopping_Service_H2H_Fault">
        <soap:fault name="VigoShopping_Service_H2H_Fault" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="VigoShopping_Service_H2H">
    <wsdl:port binding="tns:VigoShopping_Service_H2H_HTTP_Binding" name="VigoShopping_Service_H2H">
      <soap:address location="http://www.westernunion.com/VigoShopping_Service_H2H"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
