repos:
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        stages: [pre-commit]
  - repo: https://github.com/ambv/black
    rev: 24.10.0
    hooks:
      - id: black
        args: [--config=pyproject.toml]
        exclude: "migrations|snapshots"
        stages: [pre-commit]
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        args: [--config=.flake8]
        additional_dependencies: [flake8-bugbear==24.10.31]
        stages: [ pre-commit ]
