coverage:
  status:
    patch:
      default:
        target: 93%
        flags:
          - unittests

flags:
  unittests:
    paths:
      - src/
    carryforward: true

ignore:
  - "tests/**"
  - "*/migrations/**"
  - "*/commands/**"
  - "*/apps.py"
  - "*/wsgi.py"
