version: '3.8'

volumes:
  postgres_data:

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: tests
    environment:
      - SECRET_KEY=secret-key
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    ports:
      - 8000:8000
    volumes:
      - .:/code
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5