version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: prd
    environment:
      - SECRET_KEY=secret-key
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    ports:
      - 8000:8000
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://backend:80/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5