# Generated by Django 5.2.7 on 2025-10-08 06:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="system",
            options={"permissions": (("can_access_ftp", "Can access file from FTP"),)},
        ),
    ]
