# Generated by Django 5.2.10 on 2026-01-16 15:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_system_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="system",
            options={"permissions": (("can_access_ftp", "Can access files from FTP"),)},
        ),
    ]
