web = {"type": "WEB"}
agent = {"type": "AGENT"}
unicef = {"type": "H2H", "name": "UNICEF", "version": "9500"}
usd = {
    "identifier": "WGQCUS1250T",
    "reference_no": "Y3snz233UkGt1Gw4",
    "counter_id": "US125QCUSD1T",
}
eur = {"identifier": "WGQCUS125ET", "reference_no": "115210-000000003", "counter_id": "US125QCEUR1T"}

# usd = {"identifier": "GOOGDUST", "reference_no": "115210-000000003", "counter_id": "US125QCUSD1A"}
# eur = {"identifier": "MASTEUST", "reference_no": "115210-000000003", "counter_id": "XAWA"}


WMF = "WMF"
WMN = "WMN"

# delivery_services_code
MONEY_IN_TIME = "000"
WALLET = "800"

snapshot_example = {
    "id": "059a2209-666a-4cc7-8e92-9d3babac1f4a",
    "size": 2,
    "roles": [
        {
            "role": "PRIMARY",
            "individual": {
                "id": "d97bfe10-3d78-492f-950b-210668265181",
                "sex": "FEMALE",
                "email": "",
                "photo": "",
                "row_id": 57,
                "version": 1678187624350602,
                "phone_no": "+94786661137",
                "pregnant": None,
                "child_hoh": False,
                "documents": [
                    {
                        "type": "national_id",
                        "status": "VALID",
                        "cleared": False,
                        "country": "LKA",
                        "cleared_by": None,
                        "expiry_date": None,
                        "cleared_date": "2023-03-23 14:05:00",
                        "issuance_date": None,
                        "document_number": "762730977V",
                    }
                ],
                "duplicate": False,
                "full_name": "Aliyah GRAY",
                "unicef_id": "IND-23-0000.2633",
                "withdrawn": False,
                "birth_date": "1999-05-21",
                "created_at": "2023-03-07 11:29:31",
                "disability": "not disabled",
                "fchild_hoh": False,
                "given_name": "Aliyah",
                "is_removed": False,
                "updated_at": "2023-03-07 11:29:31",
                "family_name": "GRAY",
                "flex_fields": {},
                "middle_name": "",
                "user_fields": {},
                "work_status": "NOT_PROVIDED",
                "household_id": "059a2209-666a-4cc7-8e92-9d3babac1f4a",
                "last_sync_at": None,
                "relationship": "HEAD",
                "removed_date": None,
                "individual_id": "",
                "kobo_asset_id": "",
                "vector_column": "'aliyah':1 'gray':2",
                "duplicate_date": None,
                "marital_status": "",
                "phone_no_valid": True,
                "withdrawn_date": None,
                "registration_id": None,
                "business_area_id": "cf1c0bd4-2deb-4bbc-b4f6-1f4f4dc20247",
                "comms_disability": "",
                "memory_disability": "",
                "seeing_disability": "",
                "who_answers_phone": "Himself",
                "hearing_disability": "",
                "preferred_language": None,
                "age_at_registration": None,
                "observed_disability": [],
                "physical_disability": "",
                "selfcare_disability": "",
                "estimated_birth_date": False,
                "phone_no_alternative": "",
                "who_answers_alt_phone": "",
                "administration_of_rutf": None,
                "imported_individual_id": "da8d4485-09c3-4232-b114-b4faec4f4b0c",
                "last_registration_date": "2023-01-15",
                "relationship_confirmed": False,
                "first_registration_date": "2023-01-15",
                "deduplication_batch_status": "UNIQUE_IN_BATCH",
                "phone_no_alternative_valid": False,
                "deduplication_batch_results": {},
                "registration_data_import_id": "52a4d1a0-bd3a-440e-91ad-a609d45f8c10",
                "sanction_list_possible_match": False,
                "sanction_list_confirmed_match": False,
                "disability_certificate_picture": "",
                "enrolled_in_nutrition_programme": None,
                "needs_adjudication_tickets_count": 1,
                "deduplication_golden_record_status": "UNIQUE",
                "deduplication_golden_record_results": {},
            },
        }
    ],
    "start": None,
    "row_id": 57,
    "address": "75, DEVANAMPIYATISSA MAWATHA",
    "consent": True,
    "version": 1678187624103787,
    "village": "",
    "currency": "LKR",
    "deviceid": "",
    "geopoint": None,
    "returnee": None,
    "unhcr_id": "",
    "zip_code": None,
    "admin1_id": None,
    "admin2_id": None,
    "admin3_id": None,
    "admin4_id": None,
    "child_hoh": False,
    "family_id": None,
    "unicef_id": "HH-23-0000.1344",
    "withdrawn": False,
    "country_id": "3524d0f0-710b-4048-b108-9bf7f85403e7",
    "created_at": "2023-03-07 11:29:30",
    "fchild_hoh": False,
    "is_removed": False,
    "updated_at": "2023-03-07 11:29:30",
    "flex_fields": {},
    "individuals": [
        {
            "id": "d97bfe10-3d78-492f-950b-210668265181",
            "sex": "FEMALE",
            "email": "",
            "photo": "",
            "row_id": 57,
            "version": 1678187624350602,
            "phone_no": "+94786661137",
            "pregnant": None,
            "child_hoh": False,
            "documents": [
                {
                    "type": "national_id",
                    "status": "VALID",
                    "cleared": False,
                    "country": "LKA",
                    "cleared_by": None,
                    "expiry_date": None,
                    "cleared_date": "2023-03-23 14:05:00",
                    "issuance_date": None,
                    "document_number": "762730977V",
                }
            ],
            "duplicate": False,
            "full_name": "Aliyah GRAY",
            "unicef_id": "IND-23-0000.2633",
            "withdrawn": False,
            "birth_date": "1999-05-21",
            "created_at": "2023-03-07 11:29:31",
            "disability": "not disabled",
            "fchild_hoh": False,
            "given_name": "Aliyah",
            "is_removed": False,
            "updated_at": "2023-03-07 11:29:31",
            "family_name": "GRAY",
            "flex_fields": {},
            "middle_name": "",
            "user_fields": {},
            "work_status": "NOT_PROVIDED",
            "household_id": "059a2209-666a-4cc7-8e92-9d3babac1f4a",
            "last_sync_at": None,
            "relationship": "HEAD",
            "removed_date": None,
            "individual_id": "",
            "kobo_asset_id": "",
            "vector_column": "'aliyah':1 'gray':2",
            "duplicate_date": None,
            "marital_status": "",
            "phone_no_valid": True,
            "withdrawn_date": None,
            "registration_id": None,
            "business_area_id": "cf1c0bd4-2deb-4bbc-b4f6-1f4f4dc20247",
            "comms_disability": "",
            "memory_disability": "",
            "seeing_disability": "",
            "who_answers_phone": "Himself",
            "hearing_disability": "",
            "preferred_language": None,
            "age_at_registration": None,
            "observed_disability": [],
            "physical_disability": "",
            "selfcare_disability": "",
            "estimated_birth_date": False,
            "phone_no_alternative": "",
            "who_answers_alt_phone": "",
            "administration_of_rutf": None,
            "imported_individual_id": "da8d4485-09c3-4232-b114-b4faec4f4b0c",
            "last_registration_date": "2023-01-15",
            "relationship_confirmed": False,
            "first_registration_date": "2023-01-15",
            "deduplication_batch_status": "UNIQUE_IN_BATCH",
            "phone_no_alternative_valid": False,
            "deduplication_batch_results": {},
            "registration_data_import_id": "52a4d1a0-bd3a-440e-91ad-a609d45f8c10",
            "sanction_list_possible_match": False,
            "sanction_list_confirmed_match": False,
            "disability_certificate_picture": "",
            "enrolled_in_nutrition_programme": None,
            "needs_adjudication_tickets_count": 1,
            "deduplication_golden_record_status": "UNIQUE",
            "deduplication_golden_record_results": {},
        },
        {
            "id": "602b2b7e-61a9-46d2-a9f4-968175da3ffa",
            "sex": "MALE",
            "email": "",
            "photo": "",
            "row_id": 330,
            "version": 1678187624385460,
            "phone_no": "",
            "pregnant": None,
            "child_hoh": False,
            "documents": [],
            "duplicate": False,
            "full_name": "Garrett GRAY",
            "unicef_id": "IND-23-0000.2906",
            "withdrawn": False,
            "birth_date": "2022-06-07",
            "created_at": "2023-03-07 11:29:31",
            "disability": "not disabled",
            "fchild_hoh": False,
            "given_name": "Garrett",
            "is_removed": False,
            "updated_at": "2023-03-07 11:29:31",
            "family_name": "GRAY",
            "flex_fields": {},
            "middle_name": "",
            "user_fields": {},
            "work_status": "NOT_PROVIDED",
            "household_id": "059a2209-666a-4cc7-8e92-9d3babac1f4a",
            "last_sync_at": None,
            "relationship": "SON_DAUGHTER",
            "removed_date": None,
            "individual_id": "",
            "kobo_asset_id": "",
            "vector_column": "'garrett':1 'gray':2",
            "duplicate_date": None,
            "marital_status": "",
            "phone_no_valid": False,
            "withdrawn_date": None,
            "registration_id": None,
            "business_area_id": "cf1c0bd4-2deb-4bbc-b4f6-1f4f4dc20247",
            "comms_disability": "",
            "memory_disability": "",
            "seeing_disability": "",
            "who_answers_phone": "",
            "hearing_disability": "",
            "preferred_language": None,
            "age_at_registration": None,
            "observed_disability": [],
            "physical_disability": "",
            "selfcare_disability": "",
            "estimated_birth_date": False,
            "phone_no_alternative": "",
            "who_answers_alt_phone": "",
            "administration_of_rutf": None,
            "imported_individual_id": "47de75b4-e97a-467b-b421-2224e3e2641c",
            "last_registration_date": "2023-01-15",
            "relationship_confirmed": False,
            "first_registration_date": "2023-01-15",
            "deduplication_batch_status": "UNIQUE_IN_BATCH",
            "phone_no_alternative_valid": False,
            "deduplication_batch_results": {},
            "registration_data_import_id": "52a4d1a0-bd3a-440e-91ad-a609d45f8c10",
            "sanction_list_possible_match": False,
            "sanction_list_confirmed_match": False,
            "disability_certificate_picture": "",
            "enrolled_in_nutrition_programme": None,
            "needs_adjudication_tickets_count": 0,
            "deduplication_golden_record_status": "UNIQUE",
            "deduplication_golden_record_results": {},
        },
    ],
    "user_fields": {},
    "consent_sign": "",
    "last_sync_at": None,
    "removed_date": None,
    "admin_area_id": None,
    "kobo_asset_id": "",
    "children_count": 1,
    "org_enumerator": "",
    "pregnant_count": 0,
    "storage_obj_id": None,
    "withdrawn_date": None,
    "consent_sharing": [],
    "name_enumerator": "",
    "registration_id": None,
    "business_area_id": "cf1c0bd4-2deb-4bbc-b4f6-1f4f4dc20247",
    "residence_status": "",
    "country_origin_id": "3524d0f0-710b-4048-b108-9bf7f85403e7",
    "primary_collector": {
        "id": "d97bfe10-3d78-492f-950b-210668265181",
        "sex": "FEMALE",
        "email": "",
        "photo": "",
        "row_id": 57,
        "version": 1678187624350602,
        "phone_no": "+94786661137",
        "pregnant": None,
        "child_hoh": False,
        "documents": [
            {
                "type": "national_id",
                "status": "VALID",
                "cleared": False,
                "country": "LKA",
                "cleared_by": None,
                "expiry_date": None,
                "cleared_date": "2023-03-23 14:05:00",
                "issuance_date": None,
                "document_number": "762730977V",
            }
        ],
        "duplicate": False,
        "full_name": "Aliyah GRAY",
        "unicef_id": "IND-23-0000.2633",
        "withdrawn": False,
        "birth_date": "1999-05-21",
        "created_at": "2023-03-07 11:29:31",
        "disability": "not disabled",
        "fchild_hoh": False,
        "given_name": "Aliyah",
        "is_removed": False,
        "updated_at": "2023-03-07 11:29:31",
        "family_name": "GRAY",
        "flex_fields": {},
        "middle_name": "",
        "user_fields": {},
        "work_status": "NOT_PROVIDED",
        "household_id": "059a2209-666a-4cc7-8e92-9d3babac1f4a",
        "last_sync_at": None,
        "relationship": "HEAD",
        "removed_date": None,
        "individual_id": "",
        "kobo_asset_id": "",
        "vector_column": "'aliyah':1 'gray':2",
        "duplicate_date": None,
        "marital_status": "",
        "phone_no_valid": True,
        "withdrawn_date": None,
        "registration_id": None,
        "business_area_id": "cf1c0bd4-2deb-4bbc-b4f6-1f4f4dc20247",
        "comms_disability": "",
        "memory_disability": "",
        "seeing_disability": "",
        "who_answers_phone": "Himself",
        "hearing_disability": "",
        "preferred_language": None,
        "age_at_registration": None,
        "observed_disability": [],
        "physical_disability": "",
        "selfcare_disability": "",
        "estimated_birth_date": False,
        "phone_no_alternative": "",
        "who_answers_alt_phone": "",
        "administration_of_rutf": None,
        "imported_individual_id": "da8d4485-09c3-4232-b114-b4faec4f4b0c",
        "last_registration_date": "2023-01-15",
        "relationship_confirmed": False,
        "first_registration_date": "2023-01-15",
        "deduplication_batch_status": "UNIQUE_IN_BATCH",
        "phone_no_alternative_valid": False,
        "deduplication_batch_results": {},
        "registration_data_import_id": "52a4d1a0-bd3a-440e-91ad-a609d45f8c10",
        "sanction_list_possible_match": False,
        "sanction_list_confirmed_match": False,
        "disability_certificate_picture": "",
        "enrolled_in_nutrition_programme": None,
        "needs_adjudication_tickets_count": 1,
        "deduplication_golden_record_status": "UNIQUE",
        "deduplication_golden_record_results": {},
    },
    "male_children_count": 1,
    "org_name_enumerator": "",
    "registration_method": "HH_REGISTRATION",
    "total_cash_received": "41896.00",
    "head_of_household_id": "d97bfe10-3d78-492f-950b-210668265181",
    "female_children_count": 0,
    "last_registration_date": "2023-01-15 00:00:00",
    "children_disabled_count": 0,
    "collect_individual_data": "1",
    "first_registration_date": "2023-01-15 00:00:00",
    "male_age_group_60_count": 0,
    "total_cash_received_usd": "4298.32",
    "male_age_group_0_5_count": 1,
    "female_age_group_60_count": 0,
    "male_age_group_6_11_count": 0,
    "female_age_group_0_5_count": 0,
    "male_age_group_12_17_count": 0,
    "male_age_group_18_59_count": 0,
    "female_age_group_6_11_count": 0,
    "registration_data_import_id": "52a4d1a0-bd3a-440e-91ad-a609d45f8c10",
    "female_age_group_12_17_count": 0,
    "female_age_group_18_59_count": 1,
    "male_children_disabled_count": 0,
    "female_children_disabled_count": 0,
    "male_age_group_60_disabled_count": 0,
    "needs_adjudication_tickets_count": 1,
    "male_age_group_0_5_disabled_count": 0,
    "female_age_group_60_disabled_count": 0,
    "male_age_group_6_11_disabled_count": 0,
    "female_age_group_0_5_disabled_count": 0,
    "male_age_group_12_17_disabled_count": 0,
    "male_age_group_18_59_disabled_count": 0,
    "female_age_group_6_11_disabled_count": 0,
    "female_age_group_12_17_disabled_count": 0,
    "female_age_group_18_59_disabled_count": 0,
}


def iso_code(country_code, currency_code):
    return {
        "country_code": country_code,
        "currency_code": currency_code,
    }


sender = {
    "name": {
        "name_type": "C",
        "business_name": "UNICEF",
    },
    "address": {
        "addr_line1": "3 United Nations Plaza",
        "addr_line2": "",
        "city": "NEW YORK",
        "state": "NY",
        "postal_code": "10017",
        "country_code": {
            "iso_code": iso_code("US", "USD"),
            "country_name": "US",
        },
        "local_area": "NEW YORK",
        "street": "3 United Nations Plaza",
    },
    "email": "unicef@unicef.org",
    "contact_phone": "2123267000",
    "mobile_phone": {
        "phone_number": {
            "country_code": "1",
            "national_number": "2123267000",
        },
    },
    "fraud_warning_consent": "Y",
}
