<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.westernunion.com/FulfillReceiveSave_H2H" xmlns:xrsi="http://www.westernunion.com/schema/xrsi" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="FulfillReceiveSave_Service_H2H" targetNamespace="http://www.westernunion.com/FulfillReceiveSave_H2H">
  <wsdl:types>
    <xsd:schema xmlns:mrm="http://www.westernunion.com/FulfillReceiveSave" targetNamespace="http://www.westernunion.com/FulfillReceiveSave" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.westernunion.com/schema/xrsi" schemaLocation="../schema/XRSIPayOrDoNotPayRequest.xsd"/>
      <xsd:import namespace="http://www.westernunion.com/schema/xrsi" schemaLocation="../schema/XRSIErrorReply.xsd"/>
      <xsd:import namespace="http://www.westernunion.com/schema/xrsi" schemaLocation="../schema/XRSIPayOrDoNotPayReply.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="FulfillReceiveSave_in">
    <wsdl:part element="xrsi:pay-or-do-not-pay-request" name="pay-or-do-not-pay-request"/>
  </wsdl:message>
  <wsdl:message name="FulfillReceiveSave_out">
    <wsdl:part element="xrsi:pay-or-do-not-pay-reply" name="pay-or-do-not-pay-reply"/>
  </wsdl:message>
  <wsdl:message name="FulfillReceiveSave_fault1">
    <wsdl:part element="xrsi:error-reply" name="error-reply"/>
  </wsdl:message>
  <wsdl:portType name="FulfillReceiveSavePortType">
    <wsdl:operation name="FulfillReceiveSave">
      <wsdl:input message="tns:FulfillReceiveSave_in" name="FulfillReceiveSave_Input"/>
      <wsdl:output message="tns:FulfillReceiveSave_out" name="FulfillReceiveSave_Output"/>
      <wsdl:fault message="tns:FulfillReceiveSave_fault1" name="FulfillReceiveSave_Fault"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="FulfillReceiveSave_H2H_SOAP_HTTP_Binding" type="tns:FulfillReceiveSavePortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="FulfillReceiveSave">
      <soap:operation/>
      <wsdl:input name="FulfillReceiveSave_Input">
        <soap:body parts="pay-or-do-not-pay-request" use="literal"/>
      </wsdl:input>
      <wsdl:output name="FulfillReceiveSave_Output">
        <soap:body parts="pay-or-do-not-pay-reply" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="FulfillReceiveSave_Fault">
        <soap:fault name="FulfillReceiveSave_Fault" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="FulfillReceiveSave_Service_H2H">
    <wsdl:port binding="tns:FulfillReceiveSave_H2H_SOAP_HTTP_Binding" name="SOAP_HTTP_Port">
      <soap:address location="http://www.westernunion.com/FulfillReceiveSave_Service_H2H"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
