<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.westernunion.com/KYCAddCustomer"
	xmlns:xrsi="http://www.westernunion.com/kyc/schema/xrsi" xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
	xmlns:xsi="http://www.westernunion.com/schema/xrsi" 
	name="KYCAddCustomer_Service" targetNamespace="http://www.westernunion.com/KYCAddCustomer">
	<wsdl:types>
		<xsd:schema xmlns:mrm="http://www.westernunion.com/KYCAddCustomer" targetNamespace="http://www.westernunion.com/KYCAddCustomer" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="http://www.westernunion.com/schema/xrsi" schemaLocation="../schema/XRSIErrorReply.xsd"/>
			<xsd:import namespace="http://www.westernunion.com/kyc/schema/xrsi"  schemaLocation="../schema/XRSIKYCAddCustomerReply.xsd" />
			<xsd:import namespace="http://www.westernunion.com/kyc/schema/xrsi" schemaLocation="../schema/XRSIKYCAddCustomerRequest.xsd" />
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="KYCAddCustomer_in">
		<wsdl:part element="xrsi:kyc-add-customer-request" name="kyc-add-customer-request" />
	</wsdl:message>
	<wsdl:message name="KYCAddCustomer_out">
		<wsdl:part element="xrsi:kyc-add-customer-reply" name="kyc-add-customer-reply" />
	</wsdl:message>
	<wsdl:message name="KYCAddCustomer_fault1">
		<wsdl:part element="xsi:error-reply" name="error-reply" />
	</wsdl:message>
	<wsdl:portType name="KYCAddCustomerPortType">
		<wsdl:operation name="KYCAddCustomer">
			<wsdl:input message="tns:KYCAddCustomer_in" name="KYCAddCustomer_Input" />
			<wsdl:output message="tns:KYCAddCustomer_out" name="KYCAddCustomer_Output" />
			<wsdl:fault message="tns:KYCAddCustomer_fault1" name="KYCAddCustomer_Fault" />
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="KYCAddCustomer_SOAP_HTTP_Binding"
		type="tns:KYCAddCustomerPortType">
		<soap:binding style="document"
			transport="http://schemas.xmlsoap.org/soap/http" />
		<wsdl:operation name="KYCAddCustomer">
			<soap:operation />
			<wsdl:input name="KYCAddCustomer_Input">
				<soap:body parts="kyc-add-customer-request" use="literal" />
			</wsdl:input>
			<wsdl:output name="KYCAddCustomer_Output">
				<soap:body parts="kyc-add-customer-reply" use="literal" />
			</wsdl:output>
			<wsdl:fault name="KYCAddCustomer_Fault">
				<soap:fault name="KYCAddCustomer_Fault" use="literal" />
			</wsdl:fault>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="KYCAddCustomer_Service">
		<wsdl:port binding="tns:KYCAddCustomer_SOAP_HTTP_Binding" name="SOAP_HTTP_Port">
			<soap:address location="http://www.westernunion.com/KYCAddCustomer_Service" />
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
