<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.westernunion.com/KYCCustomerStatus"
	xmlns:xrsi="http://www.westernunion.com/kyc/schema/xrsi" xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
	xmlns:xsi="http://www.westernunion.com/schema/xrsi"
	name="KYCCustomerStatus_Service" targetNamespace="http://www.westernunion.com/KYCCustomerStatus">
	<wsdl:types>
		<xsd:schema xmlns:mrm="http://www.westernunion.com/KYCCustomerStatus" targetNamespace="http://www.westernunion.com/KYCCustomerStatus" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="http://www.westernunion.com/schema/xrsi" schemaLocation="../schema/XRSIErrorReply.xsd"/>
			<xsd:import namespace="http://www.westernunion.com/kyc/schema/xrsi"  schemaLocation="../schema/XRSIKYCCustomerStatusReply.xsd" />
			<xsd:import namespace="http://www.westernunion.com/kyc/schema/xrsi" schemaLocation="../schema/XRSIKYCCustomerStatusRequest.xsd" />
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="KYCCustomerStatus_in">
		<wsdl:part element="xrsi:kyc-customer-status-request" name="kyc-customer-status-request" />
	</wsdl:message>
	<wsdl:message name="KYCCustomerStatus_out">
		<wsdl:part element="xrsi:kyc-customer-status-reply" name="kyc-customer-status-reply" />
	</wsdl:message>
	<wsdl:message name="KYCCustomerStatus_fault1">
		<wsdl:part element="xsi:error-reply" name="error-reply" />
	</wsdl:message>
	<wsdl:portType name="KYCCustomerStatusPortType">
		<wsdl:operation name="KYCCustomerStatus">
			<wsdl:input message="tns:KYCCustomerStatus_in" name="KYCCustomerStatus_Input" />
			<wsdl:output message="tns:KYCCustomerStatus_out" name="KYCCustomerStatus_Output" />
			<wsdl:fault message="tns:KYCCustomerStatus_fault1" name="KYCCustomerStatus_Fault" />
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="KYCCustomerStatus_SOAP_HTTP_Binding"
		type="tns:KYCCustomerStatusPortType">
		<soap:binding style="document"
			transport="http://schemas.xmlsoap.org/soap/http" />
		<wsdl:operation name="KYCCustomerStatus">
			<soap:operation />
			<wsdl:input name="KYCCustomerStatus_Input">
				<soap:body parts="kyc-customer-status-request" use="literal" />
			</wsdl:input>
			<wsdl:output name="KYCCustomerStatus_Output">
				<soap:body parts="kyc-customer-status-reply" use="literal" />
			</wsdl:output>
			<wsdl:fault name="KYCCustomerStatus_Fault">
				<soap:fault name="KYCCustomerStatus_Fault" use="literal" />
			</wsdl:fault>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="KYCCustomerStatus_Service">
		<wsdl:port binding="tns:KYCCustomerStatus_SOAP_HTTP_Binding" name="SOAP_HTTP_Port">
			<soap:address location="http://www.westernunion.com/KYCCustomerStatus_Service" />
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
