<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.westernunion.com/ReceiptReprintSelect_H2H" xmlns:xrsi="http://www.westernunion.com/schema/xrsi" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="ReceiptReprintSelect_Service_H2H" targetNamespace="http://www.westernunion.com/ReceiptReprintSelect_H2H">
  <wsdl:types>
    <xsd:schema xmlns:mrm="http://www.westernunion.com/ReceiptReprintSelect" targetNamespace="http://www.westernunion.com/ReceiptReprintSelect" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.westernunion.com/schema/xrsi" schemaLocation="../schema/XRSIErrorReply.xsd"/>
      <xsd:import namespace="http://www.westernunion.com/schema/xrsi" schemaLocation="../schema/XRSIReceiptReprintSelectRequest.xsd"/>
      <xsd:import namespace="http://www.westernunion.com/schema/xrsi" schemaLocation="../schema/XRSIReceiptReprintSelectReply.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="ReceiptReprintSelect_Service_H2H_in">
    <wsdl:part element="xrsi:receipt-reprint-select-request" name="receipt-reprint-select-request"/>
  </wsdl:message>
  <wsdl:message name="ReceiptReprintSelect_Service_H2H_out">
    <wsdl:part element="xrsi:receipt-reprint-select-reply" name="receipt-reprint-select-reply"/>
  </wsdl:message>
  <wsdl:message name="ReceiptReprintSelect_Service_H2H_fault1">
    <wsdl:part element="xrsi:error-reply" name="error-reply"/>
  </wsdl:message>
  <wsdl:portType name="ReceiptReprintPortType">
    <wsdl:operation name="ReceiptReprintSelect_Service_H2H">
      <wsdl:input message="tns:ReceiptReprintSelect_Service_H2H_in" name="ReceiptReprintSelect_Service_H2H_Input"/>
      <wsdl:output message="tns:ReceiptReprintSelect_Service_H2H_out" name="ReceiptReprintSelect_Service_H2H_Output"/>
      <wsdl:fault message="tns:ReceiptReprintSelect_Service_H2H_fault1" name="ReceiptReprintSelect_Service_H2H_Fault"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="ReceiptReprintSelect_H2H_SOAP_HTTP_Binding" type="tns:ReceiptReprintPortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="ReceiptReprintSelect_Service_H2H">
      <soap:operation soapAction="ReceiptReprintSelect_Service_H2H"/>
      <wsdl:input name="ReceiptReprintSelect_Service_H2H_Input">
        <soap:body parts="receipt-reprint-select-request" use="literal"/>
      </wsdl:input>
      <wsdl:output name="ReceiptReprintSelect_Service_H2H_Output">
        <soap:body parts="receipt-reprint-select-reply" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="ReceiptReprintSelect_Service_H2H_Fault">
        <soap:fault name="ReceiptReprintSelect_Service_H2H_Fault" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="ReceiptReprintSelect_Service_H2H">
    <wsdl:port binding="tns:ReceiptReprintSelect_H2H_SOAP_HTTP_Binding" name="SOAP_HTTP_Port">
      <soap:address location="http://www.westernunion.com/ReceiptReprintSelect_Service_H2H"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
