# Generated by Django 4.2.5 on 2023-09-27 12:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Corridor",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.CharField(max_length=1024)),
                ("destination_country", models.CharField(max_length=2)),
                ("destination_currency", models.CharField(max_length=3)),
                ("template_code", models.CharField(max_length=4)),
                ("template", models.JSONField(blank=True, default=dict, null=True)),
            ],
        ),
    ]
