# Generated by Django 5.0.4 on 2024-06-06 19:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("western_union", "0002_alter_corridor_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceProviderCode",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=64)),
                ("code", models.CharField(max_length=32, unique=True)),
                ("country", models.CharField(max_length=2)),
                ("currency", models.CharField(max_length=3)),
            ],
        ),
    ]
