# Generated by Django 5.1.3 on 2024-12-05 12:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("western_union", "0003_serviceprovidercode"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="corridor",
            options={"permissions": (("can_view_ftp_files", "Can views Western Union FTP files"),)},
        ),
    ]
