# Generated by Django 5.1.5 on 2025-01-26 20:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("western_union", "0004_alter_corridor_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="corridor",
            options={
                "permissions": (
                    ("das_countries_currencies", "Western Union DAS: Country/Currency"),
                    (
                        "das_origination_currencies",
                        "Western Union DAS: Origination Currencies",
                    ),
                    (
                        "das_destination_currencies",
                        "Western Union DAS: Destination Currencies",
                    ),
                    (
                        "das_destination_countries",
                        "Western Union DAS: Destination Countries",
                    ),
                    ("das_delivery_services", "Western Union DAS: Delivery Services"),
                    (
                        "das_delivery_option_template",
                        "Western Union DAS: Delivery Option Template",
                    ),
                    (
                        "can_prepare_transaction",
                        "Western Union: Can Prepare Transaction",
                    ),
                    ("can_create_transaction", "Western Union: Can Create Transaction"),
                    ("can_check_status", "Western Union: Can Check Status"),
                    ("can_update_status", "Western Union: Can Update Status"),
                    ("can_search_request", "Western Union: Can Search Request"),
                    ("can_cancel_transaction", "Western Union: Can Cancel Transaction"),
                    (
                        "can_view_ftp_files",
                        "Western Union DAS: Can views Western Union FTP files",
                    ),
                )
            },
        ),
    ]
