# Generated by Django 5.1.8 on 2025-04-11 22:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PalPayGram",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "permissions": (
                    ("can_prepare_payment", "PalPay: Can Prepare Transaction"),
                    ("can_create_transaction", "PalPay: Can Create Transaction"),
                    ("can_quote_transaction", "PalPay: Can Quote Transaction"),
                    ("can_check_status", "PalPay: Can Check Status"),
                    ("can_update_status", "PalPay: Can Update Status"),
                    ("can_cancel_transaction", "PalPay: Can Cancel Transaction"),
                ),
                "managed": False,
                "default_permissions": (),
            },
        ),
    ]
