# Generated by Django 5.2.4 on 2025-09-09 08:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("palpay", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="palpaygram",
            options={
                "default_permissions": (),
                "managed": False,
                "permissions": (
                    ("can_check_profile", "PalPay: Can Check Profiles"),
                    ("can_check_balance", "PalPay: Can Check Balance"),
                    ("can_check_beneficiary", "PalPay: Can Check Beneficiary"),
                    ("can_check_transactions", "PalPay: Can Check Transactions"),
                    ("can_create_transaction", "PalPay: Can Create Transactions"),
                    ("can_check_status", "PalPay: Can Check Transaction Status"),
                    ("can_update_status", "PalPay: Can Update Transaction Status"),
                ),
            },
        ),
    ]
