# Generated by Django 5.1.5 on 2025-01-26 22:38

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MoneyGram",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "permissions": (
                    ("can_prepare_payment", "MoneyGram: Can Prepare Transaction"),
                    ("can_create_transaction", "MoneyGram: Can Create Transaction"),
                    ("can_quote_transaction", "MoneyGram: Can Quote Transaction"),
                    ("can_check_status", "MoneyGram: Can Check Status"),
                    ("can_update_status", "MoneyGram: Can Update Status"),
                    ("can_cancel_transaction", "MoneyGram: Can Cancel Transaction"),
                ),
                "managed": False,
                "default_permissions": (),
            },
        ),
    ]
