# Generated by Django 5.2.17 on 2026-09-10 09:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("moneygram", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="moneygram",
            options={
                "default_permissions": (),
                "managed": False,
                "permissions": (
                    ("can_prepare_payment", "MoneyGram: Can Prepare Transaction"),
                    ("can_draft_transaction", "MoneyGram: Can Draft Transaction"),
                    ("can_create_transaction", "MoneyGram: Can Create Transaction"),
                    ("can_commit_transaction", "MoneyGram: Can Commit Transaction"),
                    ("can_quote_transaction", "MoneyGram: Can Quote Transaction"),
                    ("can_check_status", "MoneyGram: Can Check Status"),
                    ("can_update_status", "MoneyGram: Can Update Status"),
                    ("can_cancel_transaction", "MoneyGram: Can Cancel Transaction"),
                ),
            },
        ),
    ]
