apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "hope-payment-gateway.fullname" . }}-static
  labels:
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.statics.storage | quote }}