# Generated by Django 4.2.5 on 2023-10-02 13:19

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):
    dependencies = [
        ("gateway", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentinstruction",
            name="status",
            field=django_fsm.FSMField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("OPEN", "Open"),
                    ("CLOSED", "Closed"),
                    ("READY", "Ready"),
                    ("PROCESSED", "Processed"),
                    ("ABORTED", "Aborted"),
                ],
                db_index=True,
                default="DRAFT",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="paymentrecord",
            name="status",
            field=django_fsm.FSMField(
                choices=[
                    ("PENDING", "Pending"),
                    ("VALIDATION_OK", "Validation OK"),
                    ("TRANSFERRED_TO_FSP", "Transferred to FSP"),
                    ("TRANSFERRED_TO_BENEFICIARY", "Transferred to Beneficiary"),
                    ("CANCELLED", "Cancelled"),
                    ("REFUND", "Refund"),
                    ("PURGED", "Purged"),
                    ("ERROR", "Error"),
                ],
                db_index=True,
                default="PENDING",
                max_length=50,
            ),
        ),
    ]
