# Generated by Django 4.2.7 on 2023-11-10 20:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gateway", "0002_alter_paymentinstruction_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financialserviceprovider",
            name="vision_vendor_number",
            field=models.CharField(max_length=100),
        ),
    ]
