# Generated by Django 4.2.8 on 2023-12-22 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gateway", "0003_alter_financialserviceprovider_vision_vendor_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paymentinstruction",
            name="uuid",
        ),
        migrations.RemoveField(
            model_name="paymentrecord",
            name="uuid",
        ),
        migrations.AddField(
            model_name="financialserviceprovider",
            name="remote_id",
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="paymentinstruction",
            name="remote_id",
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="paymentrecord",
            name="remote_id",
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
