# Generated by Django 4.2.9 on 2024-01-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gateway", "0005_alter_paymentrecord_remote_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentinstruction",
            name="extra",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="financialserviceprovider",
            name="vision_vendor_number",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
