# Generated by Django 4.2.9 on 2024-02-14 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gateway", "0006_paymentinstruction_extra_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialServiceProviderConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(db_index=True, max_length=16)),
                (
                    "configuration",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                (
                    "fsp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gateway.financialserviceprovider",
                    ),
                ),
            ],
            options={
                "unique_together": {("key", "fsp")},
            },
        ),
    ]
