# Generated by Django 4.2.9 on 2024-02-15 09:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gateway", "0007_financialserviceproviderconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentrecord",
            name="fsp_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=64,
                null=True,
                help_text="new MTCN for western union, transaction id for MoneyGram",
            ),
        ),
    ]
