# Generated by Django 4.2.10 on 2024-03-26 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gateway", "0009_alter_paymentrecord_record_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financialserviceprovider",
            name="remote_id",
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="paymentinstruction",
            name="remote_id",
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
