# Generated by Django 5.0.4 on 2024-04-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gateway", "0010_alter_paymentinstruction_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="financialserviceproviderconfig",
            name="label",
            field=models.CharField(blank=True, db_index=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name="financialserviceproviderconfig",
            name="key",
            field=models.CharField(db_index=True, max_length=16, unique=True),
        ),
    ]
