# Generated by Django 5.0.4 on 2024-04-12 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gateway", "0011_financialserviceproviderconfig_label_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financialserviceproviderconfig",
            name="fsp",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="configs",
                to="gateway.financialserviceprovider",
            ),
        ),
    ]
