# Generated by Django 5.0.4 on 2024-05-01 08:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gateway", "0014_paymentrecord_confirmation_code"),
    ]

    operations = [
        migrations.RenameField(
            model_name="paymentrecord",
            old_name="confirmation_code",
            new_name="auth_code",
        ),
    ]
