# Generated by Django 5.0.4 on 2024-05-14 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gateway", "0016_paymentrecord_payout_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentrecord",
            name="payout_amount",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
