# Generated by Django 5.0.4 on 2024-06-06 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gateway", "0017_alter_paymentrecord_payout_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financialserviceproviderconfig",
            name="delivery_mechanism",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="fsp", to="gateway.deliverymechanism"
            ),
        ),
    ]
