# Generated by Django 5.0.4 on 2024-06-07 10:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gateway", "0018_alter_financialserviceproviderconfig_delivery_mechanism"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financialserviceproviderconfig",
            name="key",
            field=models.CharField(db_index=True, max_length=16),
        ),
    ]
