# Generated by Django 5.0.4 on 2024-06-11 14:58

import django.db.models.deletion
import strategy_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gateway", "0019_alter_financialserviceproviderconfig_key"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExportTemplate",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("query", models.TextField()),
                ("config_key", models.CharField(max_length=32)),
                ("strategy", strategy_field.fields.StrategyField()),
                ("header", models.BooleanField(default=True)),
                ("delimiter", models.CharField(choices=[(",", ","), (";", ";"), ("|", "|"), (":", ":")], default=",")),
                ("quotechar", models.CharField(choices=[("'", "'"), ('"', '"'), ("`", "`")], default="'")),
                (
                    "quoting",
                    models.IntegerField(
                        choices=[(1, "All"), (0, "Minimal"), (3, "None"), (2, "Non Numeric")], default=1
                    ),
                ),
                ("escapechar", models.CharField(blank=True, choices=[("", ""), ("\\", "\\")], default="", null=True)),
                (
                    "delivery_mechanism",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="template",
                        to="gateway.deliverymechanism",
                    ),
                ),
                (
                    "fsp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="gateway.financialserviceprovider"
                    ),
                ),
            ],
            options={
                "unique_together": {("fsp", "config_key")},
            },
        ),
    ]
