# Generated by Django 5.0.6 on 2024-06-25 09:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gateway", "0020_exporttemplate"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentrecord",
            name="marked_for_payment",
            field=models.BooleanField(default=False),
        ),
    ]
