# Generated by Django 5.0.6 on 2024-06-27 08:19

import strategy_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gateway", "0021_paymentrecord_marked_for_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverymechanism",
            name="form",
            field=strategy_field.fields.StrategyField(blank=True, null=True),
        ),
    ]
