# Generated by Django 5.0.7 on 2024-07-18 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gateway", "0021_paymentrecord_marked_for_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverymechanism",
            name="required_fields",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="deliverymechanism",
            name="type",
            field=models.CharField(
                choices=[("IN_CASH", "In Cash"), ("VOUCHER", "Voucher"), ("DIGITAL", "Digital Asset")],
                default="IN_CASH",
                max_length=32,
            ),
            preserve_default=False,
        ),
    ]
