# Generated by Django 5.0.7 on 2024-07-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gateway", "0022_deliverymechanism_required_fields_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="deliverymechanism",
            old_name="type",
            new_name="transfer_type",
        ),
        migrations.RemoveField(
            model_name="deliverymechanism",
            name="required_fields",
        ),
        migrations.AddField(
            model_name="deliverymechanism",
            name="requirements",
            field=models.JSONField(
                blank=True,
                default=None,
                null=True,
            ),
        ),
    ]
