# Generated by Django 5.1.1 on 2024-10-10 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gateway", "0023_rename_type_deliverymechanism_transfer_type_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="financialserviceprovider",
            old_name="vision_vendor_number",
            new_name="vendor_number",
        ),
    ]
