# Generated by Django 5.1.3 on 2024-12-05 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gateway", "0025_rename_unicef_id_paymentinstruction_external_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentinstruction",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("OPEN", "Open"),
                    ("CLOSED", "Closed"),
                    ("READY", "Ready"),
                    ("PROCESSED", "Processed"),
                    ("FINALIZED", "Finalized"),
                    ("ABORTED", "Aborted"),
                ],
                db_index=True,
                default="DRAFT",
                max_length=50,
            ),
        ),
    ]
