# Generated by Django 5.1.5 on 2025-01-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gateway", "0026_alter_paymentinstruction_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentrecord",
            name="payout_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
