# Generated by Django 5.1.5 on 2025-01-26 20:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gateway", "0027_paymentrecord_payout_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="exporttemplate",
            options={
                "permissions": (
                    ("can_import_records", "Can Import Records"),
                    ("can_export_records", "Can Export Records"),
                )
            },
        ),
    ]
