# Generated by Django 5.1.5 on 2025-02-05 15:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gateway", "0029_asyncjob"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paymentrecord",
            name="marked_for_payment",
        ),
    ]
