# Generated by Django 5.1.6 on 2025-02-19 15:49

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gateway", "0030_remove_paymentrecord_marked_for_payment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Office",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "remote_id",
                    models.CharField(blank=True, max_length=100, null=True, unique=True),
                ),
                (
                    "long_name",
                    models.CharField(blank=True, db_index=True, max_length=100, null=True),
                ),
                (
                    "name",
                    models.CharField(blank=True, db_index=True, max_length=100, null=True),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(blank=True, max_length=100, null=True, unique=True),
                ),
                ("active", models.BooleanField(default=False)),
                (
                    "supervised",
                    models.BooleanField(
                        default=False,
                        help_text="Flag to enable/disable offices, which need manual check",
                    ),
                ),
                ("extra_fields", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="paymentinstruction",
            name="office",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="gateway.office",
            ),
        ),
    ]
