# Generated by Django 5.1.6 on 2025-02-24 09:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gateway", "0031_office_paymentinstruction_office"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="office",
            name="active",
        ),
        migrations.AddField(
            model_name="paymentinstruction",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
