# Generated by Django 5.1.6 on 2025-03-25 23:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gateway", "0033_accounttype_deliverymechanism_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financialserviceproviderconfig",
            name="required_fields",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=list,
                help_text="comma separated list of unique fields",
                null=True,
                size=None,
            ),
        ),
    ]
