# Generated by Django 5.1.6 on 2025-04-03 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gateway", "0035_alter_accounttype_unique_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliverymechanism",
            name="account_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="delivery_mechanisms",
                to="gateway.accounttype",
            ),
        ),
    ]
