# Generated by Django 5.1.8 on 2025-04-03 18:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gateway", "0036_alter_deliverymechanism_account_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deliverymechanism",
            name="requirements",
        ),
    ]
