# Generated by Django 5.1.8 on 2025-04-07 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gateway", "0037_remove_deliverymechanism_requirements"),
    ]

    operations = [
        migrations.AddField(
            model_name="financialserviceproviderconfig",
            name="office",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="configs",
                to="gateway.office",
            ),
        ),
    ]
