# Generated by Django 5.1.8 on 2025-04-10 18:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gateway", "0038_financialserviceproviderconfig_office"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentrecord",
            name="record_code",
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
    ]
