# Generated by Django 5.1.8 on 2025-04-15 11:51

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gateway", "0039_alter_paymentrecord_record_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("short_name", models.CharField(db_index=True, max_length=255)),
                ("iso_code2", models.CharField(max_length=2, unique=True)),
                ("iso_code3", models.CharField(max_length=3, unique=True)),
                ("iso_num", models.CharField(max_length=4, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterUniqueTogether(
            name="financialserviceproviderconfig",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="financialserviceproviderconfig",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="configs",
                to="gateway.country",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="financialserviceproviderconfig",
            unique_together={("country", "fsp", "delivery_mechanism")},
        ),
    ]
