# Generated by Django 5.2 on 2025-04-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gateway", "0040_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exporttemplate",
            name="delimiter",
            field=models.CharField(
                choices=[(",", ","), (";", ";"), ("|", "|"), (":", ":")],
                default=",",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="exporttemplate",
            name="escapechar",
            field=models.CharField(
                blank=True,
                choices=[("", ""), ("\\", "\\")],
                default="",
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="exporttemplate",
            name="quotechar",
            field=models.CharField(choices=[("'", "'"), ('"', '"'), ("`", "`")], default="'", max_length=1),
        ),
        migrations.AlterField(
            model_name="paymentinstruction",
            name="tag",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
