# Generated by Django 5.2 on 2025-05-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gateway", "0041_alter_exporttemplate_delimiter_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financialserviceproviderconfig",
            name="label",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
