# Generated by Django 5.2.1 on 2025-05-20 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gateway", "0042_alter_financialserviceproviderconfig_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliverymechanism",
            name="account_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="delivery_mechanisms",
                to="gateway.accounttype",
            ),
        ),
    ]
