# Generated by Django 5.2.3 on 2025-06-19 09:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gateway", "0044_rename_extra_data_paymentrecord_fsp_data_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentrecord",
            name="extra_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Useful information related original record",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="paymentrecord",
            name="fsp_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="FSP data stored for troubleshooting",
                null=True,
            ),
        ),
    ]
