# Generated by Django 5.2.11 on 2026-03-15 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gateway", "0045_paymentrecord_extra_data_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exporttemplate",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="template",
                to="gateway.country",
            ),
        ),
        migrations.AddField(
            model_name="exporttemplate",
            name="office",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="template",
                to="gateway.office",
            ),
        ),
        migrations.AddField(
            model_name="paymentinstruction",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="gateway.country",
            ),
        ),
        migrations.AddField(
            model_name="paymentinstruction",
            name="delivery_mechanism",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="gateway.deliverymechanism",
            ),
        ),
        migrations.AddField(
            model_name="paymentinstruction",
            name="export",
            field=models.ForeignKey(
                blank=True,
                help_text="this is intent to be used only to force a template for a payment instruction",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="gateway.exporttemplate",
            ),
        ),
        migrations.AlterField(
            model_name="exporttemplate",
            name="delivery_mechanism",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="template",
                to="gateway.deliverymechanism",
            ),
        ),
        migrations.AlterField(
            model_name="exporttemplate",
            name="fsp",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="gateway.financialserviceprovider",
            ),
        ),
        migrations.AlterField(
            model_name="paymentinstruction",
            name="fsp",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="gateway.financialserviceprovider",
            ),
        ),
        migrations.AlterField(
            model_name="paymentrecord",
            name="parent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="records",
                to="gateway.paymentinstruction",
            ),
        ),
    ]
