# Generated by Django 5.2.11 on 2026-03-18 19:09

import strategy_field.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gateway", "0046_exporttemplate_country_exporttemplate_office_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exporttemplate",
            name="strategy",
            field=strategy_field.fields.StrategyField(blank=True, null=True),
        ),
    ]
