# Generated by Django 5.2.17 on 2026-09-23 19:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gateway", "0048_convert_unique_together_to_constraints"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paymentrecord",
            options={"permissions": (("can_cancel_records", "Can Cancel Records"),)},
        ),
    ]
