# Generated by Django 4.2.4 on 2023-09-07 10:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("western_union", "0002_log_corridor_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="log",
            old_name="transaction_number",
            new_name="transaction_id",
        ),
        migrations.AddField(
            model_name="log",
            name="extra_data",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="log",
            name="message",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
