# Generated by Django 4.2.4 on 2023-09-08 19:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("western_union", "0005_log_success"),
    ]

    operations = [
        migrations.RenameField(
            model_name="log",
            old_name="transaction_id",
            new_name="record_code",
        ),
    ]
