# Generated by Django 4.2.4 on 2023-09-13 20:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("western_union", "0007_rename_log_paymentrecordlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentrecordlog",
            name="payload",
            field=models.JSONField(default=dict),
        ),
    ]
