# Generated by Django 4.2.4 on 2023-09-14 00:06

import django.utils.timezone
import django_fsm
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("western_union", "0008_paymentrecordlog_payload"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentInstruction",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("unicef_id", models.CharField(db_index=True, max_length=255)),
                (
                    "status",
                    django_fsm.FSMField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("OPEN", "Open"),
                            ("CLOSED", "Closed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=50,
                    ),
                ),
                ("payload", models.JSONField(default=dict)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
