# Generated by Django 4.2.4 on 2023-09-14 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("western_union", "0009_paymentinstruction"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentrecordlog",
            name="parent",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="western_union.paymentinstruction"
            ),
            preserve_default=False,
        ),
    ]
