# Generated by Django 4.2.4 on 2023-09-22 01:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("western_union", "0015_rename_paymentrecordlog_paymentrecord"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentrecord",
            name="message",
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
    ]
