# Generated by Django 4.2.5 on 2023-09-26 10:11

from django.db import migrations, models
import strategy_field.fields


class Migration(migrations.Migration):
    dependencies = [
        ("western_union", "0016_alter_paymentrecord_message"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialServiceProvider",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=64, unique=True)),
                ("vision_vendor_number", models.CharField(max_length=100, unique=True)),
                ("strategy", strategy_field.fields.StrategyField()),
                ("configuration", models.JSONField(default={})),
            ],
        ),
    ]
