# Generated by Django 4.2.5 on 2023-09-26 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_system_name"),
        ("western_union", "0017_financialserviceprovider"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentinstruction",
            name="fsp",
            field=models.ForeignKey(
                default=2, on_delete=django.db.models.deletion.CASCADE, to="western_union.financialserviceprovider"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="paymentinstruction",
            name="system",
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to="core.system"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="paymentinstruction",
            name="tag",
            field=models.CharField(blank=True, null=True),
        ),
    ]
