# Generated by Django 4.2.5 on 2023-09-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("western_union", "0018_paymentinstruction_fsp_paymentinstruction_system_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="corridor",
            name="template",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="financialserviceprovider",
            name="configuration",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="paymentinstruction",
            name="payload",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="paymentrecord",
            name="extra_data",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="paymentrecord",
            name="payload",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
