<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.westernunion.com/CancelPaid_Service_H2H" xmlns:xrsi="http://www.westernunion.com/schema/xrsi" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="CancelPaid_Service_H2H" targetNamespace="http://www.westernunion.com/CancelPaid_Service_H2H">
  <wsdl:types>
    <xsd:schema xmlns:mrm="http://www.westernunion.com/CancelPaid_Service_H2H" targetNamespace="http://www.westernunion.com/CancelPaid_Service_H2H" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.westernunion.com/schema/xrsi" schemaLocation="../schema/XRSICancelPaidRequest.xsd"/>
      <xsd:import namespace="http://www.westernunion.com/schema/xrsi" schemaLocation="../schema/XRSIErrorReply.xsd"/>
      <xsd:import namespace="http://www.westernunion.com/schema/xrsi" schemaLocation="../schema/XRSICancelPaidReply.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="CancelPaid_in">
    <wsdl:part element="xrsi:cancel-paid-request" name="cancel-paid-request"/>
  </wsdl:message>
  <wsdl:message name="CancelPaid_out">
    <wsdl:part element="xrsi:cancel-paid-reply" name="cancel-paid-reply"/>
  </wsdl:message>
  <wsdl:message name="CancelPaid_fault1">
    <wsdl:part element="xrsi:error-reply" name="error-reply"/>
  </wsdl:message>
  <wsdl:portType name="CancelPaidPortType">
    <wsdl:operation name="CancelPaid">
      <wsdl:input message="tns:CancelPaid_in" name="CancelPaid_Input"/>
      <wsdl:output message="tns:CancelPaid_out" name="CancelPaid_Output"/>
      <wsdl:fault message="tns:CancelPaid_fault1" name="CancelPaid_Fault"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="CancelPaid_Service_H2H_SOAP_HTTP_Binding" type="tns:CancelPaidPortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="CancelPaid">
      <soap:operation/>
      <wsdl:input name="CancelPaid_Input">
        <soap:body parts="cancel-paid-request" use="literal"/>
      </wsdl:input>
      <wsdl:output name="CancelPaid_Output">
        <soap:body parts="cancel-paid-reply" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="CancelPaid_Fault">
        <soap:fault name="CancelPaid_Fault" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="CancelPaid_Service_H2H">
    <wsdl:port binding="tns:CancelPaid_Service_H2H_SOAP_HTTP_Binding" name="SOAP_HTTP_Port">
      <soap:address location="http://localhost:7800/CancelPaid_Service_H2H"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
