<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.westernunion.com/FulfillReceiveSearch_H2H" xmlns:xrsi="http://www.westernunion.com/schema/xrsi" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="FulfillReceiveSearchService_H2H" targetNamespace="http://www.westernunion.com/FulfillReceiveSearch_H2H">
  <wsdl:types>
    <xsd:schema xmlns:mrm="http://www.westernunion.com/FulfillReceiveSearch" targetNamespace="http://www.westernunion.com/FulfillReceiveSearch" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.westernunion.com/schema/xrsi" schemaLocation="../schema/XRSIStagedReceiveMoneySearchReply.xsd"/>
      <xsd:import namespace="http://www.westernunion.com/schema/xrsi" schemaLocation="../schema/XRSIErrorReply.xsd"/>
      <xsd:import namespace="http://www.westernunion.com/schema/xrsi" schemaLocation="../schema/XRSIStagedReceiveMoneySearchRequest.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="FulfillReceiveSearch_in">
    <wsdl:part element="xrsi:staged-receive-money-search-request" name="staged-receive-money-search-request"/>
  </wsdl:message>
  <wsdl:message name="FulfillReceiveSearch_out">
    <wsdl:part element="xrsi:staged-receive-money-search-reply" name="staged-receive-money-search-reply"/>
  </wsdl:message>
  <wsdl:message name="FulfillReceiveSearch_fault1">
    <wsdl:part element="xrsi:error-reply" name="error-reply"/>
  </wsdl:message>
  <wsdl:portType name="FulfillReceiveSearchPortType">
    <wsdl:operation name="FulfillReceiveSearch">
      <wsdl:input message="tns:FulfillReceiveSearch_in" name="FulfillReceiveSearch_Input"/>
      <wsdl:output message="tns:FulfillReceiveSearch_out" name="FulfillReceiveSearch_Output"/>
      <wsdl:fault message="tns:FulfillReceiveSearch_fault1" name="FulfillReceiveSearch_Fault"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="FulfillReceiveSearch_H2H_SOAP_HTTP_Binding" type="tns:FulfillReceiveSearchPortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="FulfillReceiveSearch">
      <soap:operation soapAction="FulfillReceiveSearchAction"/>
      <wsdl:input name="FulfillReceiveSearch_Input">
        <soap:body parts="staged-receive-money-search-request" use="literal"/>
      </wsdl:input>
      <wsdl:output name="FulfillReceiveSearch_Output">
        <soap:body parts="staged-receive-money-search-reply" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="FulfillReceiveSearch_Fault">
        <soap:fault name="FulfillReceiveSearch_Fault" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="FulfillReceiveSearchService_H2H">
    <wsdl:port binding="tns:FulfillReceiveSearch_H2H_SOAP_HTTP_Binding" name="SOAP_HTTP_Port">
      <soap:address location="http://www.westernunion.com/FulfillReceiveSearchService_H2H"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
