<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.westernunion.com/DigitalImageLookup_2" xmlns:xrsi="http://www.westernunion.com/kyc/schema/xrsi" xmlns:xsi="http://www.westernunion.com/schema/xrsi" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="DigitalImageLookup_2_Service" targetNamespace="http://www.westernunion.com/DigitalImageLookup_2">
  <wsdl:types>
    <xsd:schema xmlns:mrm="http://www.westernunion.com/DigitalImageLookup_2" targetNamespace="http://www.westernunion.com/DigitalImageLookup_2" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.westernunion.com/kyc/schema/xrsi" schemaLocation="../schema/XRSIDigitalImageLookupRequest_2.xsd"/>
      <xsd:import namespace="http://www.westernunion.com/kyc/schema/xrsi" schemaLocation="../schema/XRSIDigitalImageLookupReply_2.xsd"/>
      <xsd:import namespace="http://www.westernunion.com/schema/xrsi" schemaLocation="../schema/XRSIErrorReply.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="DigitalImageLookup_2_in">
    <wsdl:part element="xrsi:digital-image-lookup-request-2" name="digital-image-lookup-request-2"/>
  </wsdl:message>
  <wsdl:message name="DigitalImageLookup_2_out">
    <wsdl:part element="xrsi:digital-image-lookup-reply-2" name="digital-image-lookup-reply-2"/>
  </wsdl:message>
  <wsdl:message name="DigitalImageLookup_2_fault1">
    <wsdl:part element="xsi:error-reply" name="error-reply"/>
  </wsdl:message>
  <wsdl:portType name="DigitalImageLookupPortType_2">
    <wsdl:operation name="DigitalImageLookup_2">
      <wsdl:input message="tns:DigitalImageLookup_2_in" name="DigitalImageLookup_2_Input"/>
      <wsdl:output message="tns:DigitalImageLookup_2_out" name="DigitalImageLookup_2_Output"/>
      <wsdl:fault message="tns:DigitalImageLookup_2_fault1" name="DigitalImageLookup_2_Fault"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="DigitalImageLookup_2_SOAP_HTTP_Binding" type="tns:DigitalImageLookupPortType_2">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="DigitalImageLookup_2">
      <soap:operation/>
      <wsdl:input name="DigitalImageLookup_2_Input">
        <soap:body parts="digital-image-lookup-request-2" use="literal"/>
      </wsdl:input>
      <wsdl:output name="DigitalImageLookup_2_Output">
        <soap:body parts="digital-image-lookup-reply-2" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="DigitalImageLookup_2_Fault">
        <soap:fault name="DigitalImageLookup_2_Fault" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="DigitalImageLookup_Service_2">
    <wsdl:port binding="tns:DigitalImageLookup_2_SOAP_HTTP_Binding" name="SOAP_HTTP_Port">
      <soap:address location="http://www.westernunion.com/DigitalImageLookup_Service_2"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
