<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.westernunion.com/ModifyOperator_H2H" xmlns:xrsi="http://www.westernunion.com/operator/schema/xrsi" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.westernunion.com/schema/xrsi" name="ModifyOperator_Service_H2H" targetNamespace="http://www.westernunion.com/ModifyOperator_H2H">
  <wsdl:types>
    <xsd:schema xmlns:mrm="http://www.westernunion.com/ModifyOperator_H2H" targetNamespace="http://www.westernunion.com/ModifyOperator_H2H" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.westernunion.com/operator/schema/xrsi" schemaLocation="../schema/XRSIModifyOperatorRequest.xsd"/>
      <xsd:import namespace="http://www.westernunion.com/schema/xrsi" schemaLocation="../schema/XRSIErrorReply.xsd"/>
      <xsd:import namespace="http://www.westernunion.com/operator/schema/xrsi" schemaLocation="../schema/XRSIModifyOperatorReply.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="ModifyOperator_in">
    <wsdl:part element="xrsi:modify_operator_request" name="modify_operator_request"/>
  </wsdl:message>
  <wsdl:message name="ModifyOperator_out">
    <wsdl:part element="xrsi:modify_operator_reply" name="modify_operator_reply"/>
  </wsdl:message>
  <wsdl:message name="ModifyOperator_fault">
    <wsdl:part element="xsi:error-reply" name="error-reply"/>
  </wsdl:message>
  <wsdl:portType name="ModifyOperatorPortType">
    <wsdl:operation name="ModifyOperator">
      <wsdl:input message="tns:ModifyOperator_in" name="ModifyOperator_Input"/>
      <wsdl:output message="tns:ModifyOperator_out" name="ModifyOperator_Output"/>
      <wsdl:fault message="tns:ModifyOperator_fault" name="ModifyOperator_Fault"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="ModifyOperator_H2H_SOAP_HTTP_Binding" type="tns:ModifyOperatorPortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="ModifyOperator">
      <soap:operation soapAction="ModifyOperator_Action"/>
      <wsdl:input name="ModifyOperator_Input">
        <soap:body parts="modify_operator_request" use="literal"/>
      </wsdl:input>
      <wsdl:output name="ModifyOperator_Output">
        <soap:body parts="modify_operator_reply" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="ModifyOperator_Fault">
        <soap:fault name="ModifyOperator_Fault" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="ModifyOperator_Service_H2H">
    <wsdl:port binding="tns:ModifyOperator_H2H_SOAP_HTTP_Binding" name="SOAP_HTTP_Port">
      <soap:address location="http://www.westernunion.com/ModifyOperator_Service_H2H"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
