<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.westernunion.com/OperatorRegistration_H2H" xmlns:xrsi="http://www.westernunion.com/operator/schema/xrsi" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.westernunion.com/schema/xrsi" name="OperatorRegistration_Service_H2H" targetNamespace="http://www.westernunion.com/OperatorRegistration_H2H">
  <wsdl:types>
    <xsd:schema xmlns:mrm="http://www.westernunion.com/OperatorRegistration_H2H" targetNamespace="http://www.westernunion.com/OperatorRegistration_H2H" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.westernunion.com/operator/schema/xrsi" schemaLocation="../schema/XRSIOperatorRegistrationRequest.xsd"/>
      <xsd:import namespace="http://www.westernunion.com/schema/xrsi" schemaLocation="../schema/XRSIErrorReply.xsd"/>
      <xsd:import namespace="http://www.westernunion.com/operator/schema/xrsi" schemaLocation="../schema/XRSIOperatorRegistrationReply.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="OperatorRegistration_in">
    <wsdl:part element="xrsi:operator_registration_request" name="operator_registration_request"/>
  </wsdl:message>
  <wsdl:message name="OperatorRegistration_out">
    <wsdl:part element="xrsi:operator_registration_reply" name="operator_registration_reply"/>
  </wsdl:message>
  <wsdl:message name="OperatorRegistration_fault">
    <wsdl:part element="xsi:error-reply" name="error-reply"/>
  </wsdl:message>
  <wsdl:portType name="OperatorRegistrationPortType">
    <wsdl:operation name="OperatorRegistration">
      <wsdl:input message="tns:OperatorRegistration_in" name="OperatorRegistration_Input"/>
      <wsdl:output message="tns:OperatorRegistration_out" name="OperatorRegistration_Output"/>
      <wsdl:fault message="tns:OperatorRegistration_fault" name="OperatorRegistration_Fault"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="OperatorRegistration_H2H_SOAP_HTTP_Binding" type="tns:OperatorRegistrationPortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="OperatorRegistration">
      <soap:operation soapAction="OperatorRegistration_Action"/>
      <wsdl:input name="OperatorRegistration_Input">
        <soap:body parts="operator_registration_request" use="literal"/>
      </wsdl:input>
      <wsdl:output name="OperatorRegistration_Output">
        <soap:body parts="operator_registration_reply" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="OperatorRegistration_Fault">
        <soap:fault name="OperatorRegistration_Fault" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="OperatorRegistration_Service_H2H">
    <wsdl:port binding="tns:OperatorRegistration_H2H_SOAP_HTTP_Binding" name="SOAP_HTTP_Port">
      <soap:address location="http://www.westernunion.com/OperatorRegistration_Service_H2H"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
