<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.westernunion.com/PasswordAdministration_H2H" xmlns:xrsi="http://www.westernunion.com/schema/xrsi" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="PasswordAdmin_Service_H2H" targetNamespace="http://www.westernunion.com/PasswordAdministration_H2H">
  <wsdl:types>
    <xsd:schema xmlns:mrm="http://www.westernunion.com/PasswordAdministration" targetNamespace="http://www.westernunion.com/PasswordAdministration" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
          <xsd:import namespace="http://www.westernunion.com/schema/xrsi" schemaLocation="../schema/XRSIPasswordAdministrationRequest.xsd"/>
          <xsd:import namespace="http://www.westernunion.com/schema/xrsi" schemaLocation="../schema/XRSIPasswordAdministrationReply.xsd"/>
          <xsd:import namespace="http://www.westernunion.com/schema/xrsi" schemaLocation="../schema/XRSIErrorReply.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="PasswordAdmin_in">
    <wsdl:part element="xrsi:password-admin-request" name="password-admin-request"/>
  </wsdl:message>
  <wsdl:message name="PasswordAdmin_out">
    <wsdl:part element="xrsi:password-admin-reply" name="password-admin-reply"/>
  </wsdl:message>
  <wsdl:message name="PasswordAdmin_fault1">
      <wsdl:part element="xrsi:error-reply" name="error-reply"/>
  </wsdl:message>
  <wsdl:portType name="PasswordAdminPortType">
    <wsdl:operation name="PasswordAdmin">
      <wsdl:input message="tns:PasswordAdmin_in" name="PasswordAdmin_Input"/>
      	<wsdl:output message="tns:PasswordAdmin_out" name="PasswordAdmin_Output"/>
      <wsdl:fault message="tns:PasswordAdmin_fault1" name="PasswordAdmin_Fault"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="PasswordAdmin_H2H_SOAP_HTTP_Binding" type="tns:PasswordAdminPortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="PasswordAdmin">
          <soap:operation soapAction="PasswordAdminAction"/>
          <wsdl:input name="PasswordAdmin_Input">
            <soap:body parts="password-admin-request" use="literal"/>
          </wsdl:input>
          <wsdl:output name="PasswordAdmin_Output">
            <soap:body parts="password-admin-reply" use="literal"/>
          </wsdl:output>
          <wsdl:fault name="PasswordAdmin_Fault">
            <soap:fault name="PasswordAdmin_Fault" use="literal"/>
          </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="PasswordAdmin_Service_H2H">
    <wsdl:port binding="tns:PasswordAdmin_H2H_SOAP_HTTP_Binding" name="SOAP_HTTP_Port">
      <soap:address location="http://www.westernunion.com/PasswordAdmin_Service_H2H"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
