# Generated by Django 4.2.3 on 2023-08-17 07:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hope", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentHouseholdSnapshot",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("snapshot_data", models.JSONField(default=dict)),
                ("household_id", models.UUIDField()),
            ],
            options={
                "db_table": "payment_paymenthouseholdsnapshot",
                "managed": False,
            },
        ),
    ]
