# Generated by Django 4.2.3 on 2023-08-28 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Corridor",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("destination_country", models.CharField(max_length=2)),
                ("destination_currency", models.CharField(max_length=3)),
                ("template_code", models.CharField(max_length=4)),
                ("template", models.JSONField(default=dict)),
            ],
        ),
    ]
