# Generated by Django 4.2.4 on 2023-09-07 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("western_union", "0003_rename_transaction_number_log_transaction_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="log",
            name="transaction_id",
            field=models.CharField(max_length=64),
        ),
    ]
