# Generated by Django 4.2.4 on 2023-09-08 08:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("western_union", "0004_alter_log_transaction_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="log",
            name="success",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
