# Generated by Django 4.2.4 on 2023-09-08 19:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("western_union", "0006_rename_transaction_id_log_record_code"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Log",
            new_name="PaymentRecordLog",
        ),
    ]
