# Generated by Django 4.2.4 on 2023-09-19 17:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("western_union", "0012_paymentinstruction_uuid_paymentrecordlog_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentinstruction",
            name="uuid",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="paymentrecordlog",
            name="uuid",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
