# Generated by Django 4.2.4 on 2023-09-22 00:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("western_union", "0014_alter_paymentinstruction_status"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PaymentRecordLog",
            new_name="PaymentRecord",
        ),
    ]
