from .. import env

DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL")
SERVER_EMAIL = "root@localhost"
EMAIL_BACKEND = env("EMAIL_BACKEND")

ANYMAIL = {
    "MAILJET_API_URL": env("MAILJET_API_URL"),
    "MAILJET_API_KEY": env("MAILJET_API_KEY"),
    "MAILJET_SECRET_KEY": env("MAILJET_SECRET_KEY"),
    "IGNORE_RECIPIENT_STATUS": env("IGNORE_RECIPIENT_STATUS"),
    "IGNORE_UNSUPPORTED_FEATURES": env("IGNORE_UNSUPPORTED_FEATURES"),
    "REQUESTS_TIMEOUT": env("REQUESTS_TIMEOUT"),
    "DEBUG_API_REQUESTS": env("DEBUG_API_REQUESTS"),
}
