from ..settings import env

MONEYGRAM_HOST = env("MONEYGRAM_HOST")
MONEYGRAM_CLIENT_ID = env("MONEYGRAM_CLIENT_ID")
MONEYGRAM_CLIENT_SECRET = env("MONEYGRAM_CLIENT_SECRET")
MONEYGRAM_REGISTRATION_NUMBER = env("MONEYGRAM_REGISTRATION_NUMBER")
MONEYGRAM_PUBLIC_KEY = env("MONEYGRAM_PUBLIC_KEY")
