from ..settings import env

WESTERN_UNION_BASE_URL = env("WESTERN_UNION_BASE_URL")
WESTERN_UNION_CERT = env("WESTERN_UNION_CERT")
WESTERN_UNION_KEY = env("WESTERN_UNION_KEY")

FTP_WESTERN_UNION_SERVER = env("FTP_WESTERN_UNION_SERVER")
FTP_WESTERN_UNION_USERNAME = env("FTP_WESTERN_UNION_USERNAME")
FTP_WESTERN_UNION_PASSWORD = env("FTP_WESTERN_UNION_PASSWORD")
FTP_WESTERN_UNION_PORT = env("FTP_WESTERN_UNION_PORT")
