# Generated by Django 5.2.13 on 2026-04-15 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hope_api_auth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="apilogentry",
            name="token_new",
            field=models.ForeignKey(
                db_column="token_key",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.HOPE_API_AUTH_APITOKEN_MODEL,
                to_field="key",
            ),
        ),
    ]
