# Generated by Django 5.2.13 on 2026-04-15 09:43

from django.db import migrations


def copy_token_fk(apps, schema_editor):
    APILogEntry = apps.get_model("hope_api_auth", "APILogEntry")
    APIToken = apps.get_model("hope_api_auth", "APIToken")

    # Build mapping: id → key
    token_map = dict(APIToken.objects.all().values_list("id", "key"))

    batch = []

    for log in APILogEntry.objects.all().iterator(chunk_size=1000):
        key = token_map.get(log.token_id)

        if key:
            log.token_new_id = key
            batch.append(log)

        if len(batch) >= 1000:
            APILogEntry.objects.bulk_update(batch, ["token_new_id"])
            batch = []

    if batch:
        APILogEntry.objects.bulk_update(batch, ["token_new_id"])


class Migration(migrations.Migration):
    dependencies = [
        ("hope_api_auth", "0002_apilogentry_token_new"),
    ]

    operations = [
        migrations.RunPython(copy_token_fk, migrations.RunPython.noop),
    ]
