# Generated by Django 5.2.14 on 2026-06-05 09:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hope_api_auth", "0003_auto_20260415_0443"),
    ]

    operations = [
        migrations.RenameField(
            model_name="apilogentry",
            old_name="token",
            new_name="token_old",
        ),
    ]
