# Generated by Django 5.2.14 on 2026-06-05 09:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hope_api_auth", "0004_rename_token_apilogentry_token_old"),
    ]

    operations = [
        migrations.RenameField(
            model_name="apilogentry",
            old_name="token_new",
            new_name="token",
        ),
    ]
