# Generated by Django 5.2.14 on 2026-06-05 09:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hope_api_auth", "0005_rename_token_new_apilogentry_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="apitoken",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Created",
            ),
            preserve_default=False,
        ),
    ]
