# Generated by Django 5.2.15 on 2026-06-09 12:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hope_api_auth", "0006_apitoken_created"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apilogentry",
            name="token_old",
        ),
    ]
