# Generated by Django 5.2.15 on 2026-06-29 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hope_api_auth", "0007_remove_apilogentry_token_old"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="apitoken",
            name="key",
            field=models.CharField(max_length=40, unique=True, verbose_name="Key"),
        ),
        migrations.AlterField(
            model_name="apitoken",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="auth_token",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
