# Generated by Django 5.2.15 on 2026-06-29 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hope_api_auth", "0008_alter_apitoken_key_alter_apitoken_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apilogentry",
            name="token",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.HOPE_API_AUTH_APITOKEN_MODEL,
            ),
        ),
    ]
