[uwsgi]

http-socket = 0.0.0.0:8000
virtualenv=/venv
enable-threads=0
honour-range=1
processes = 4
master=1
module=hope_payment_gateway.config.wsgi
buffer-size = 8192
http-buffer-size = 8192

static-gzip-all=true
http-keepalive = 1
collect-header=Content-Type RESPONSE_CONTENT_TYPE

chdir=app/
uid = hope
gid = unicef
mimefile=/conf/mime.types
